// Generated by tools/gen_alarm_font.py -- DO NOT EDIT BY HAND.
// Re-run the generator instead; tools/check_alarm_font_transcription.py
// compares this file against a fresh render, bit for bit.
//
// Included from inside alarm_overlay.v's module body, so this file holds
// a bare function and must NOT be added to the .al file list.
//
// Glyphs    : 紧急疏散火警出口 (index order 0=紧 1=急 2=疏 3=散 4=火 5=警 6=出 7=口)
// Font      : C:/Windows/Fonts/simhei.ttf @ 24 px, threshold 110
// Cells     : 24 x 24 px, displayed x2 on a 64 px pitch (8 px gutter each side)
// Bit order : bit 23 is the leftmost column of the row.
// The words these glyphs spell are in alarm_overlay.v, not here; see
// gen_alarm_font.py:check_rtl_words for the cross-check.
// Blank rows are folded into the default arm to keep the file short.
// The argument is cell_idx, not cell: `cell` is a Verilog-2001 reserved
// word and TD rejects it with HDL-8007.

function [23:0] alarm_glyph;
    input [2:0] cell_idx;
    input [4:0] row;
    begin
        case (cell_idx)
            3'd0: case (row)   // 紧
                5'd1: alarm_glyph = 24'h030000;
                5'd2: alarm_glyph = 24'h337FF0;
                5'd3: alarm_glyph = 24'h331870;
                5'd4: alarm_glyph = 24'h331C60;
                5'd5: alarm_glyph = 24'h330CC0;
                5'd6: alarm_glyph = 24'h330780;
                5'd7: alarm_glyph = 24'h330FC0;
                5'd8: alarm_glyph = 24'h333CF8;
                5'd9: alarm_glyph = 24'h03B038;
                5'd10: alarm_glyph = 24'h01C300;
                5'd11: alarm_glyph = 24'h070F00;
                5'd12: alarm_glyph = 24'h1FFC00;
                5'd13: alarm_glyph = 24'h0CF180;
                5'd14: alarm_glyph = 24'h03C0C0;
                5'd15: alarm_glyph = 24'h1FFFE0;
                5'd16: alarm_glyph = 24'h3FFF70;
                5'd17: alarm_glyph = 24'h023120;
                5'd18: alarm_glyph = 24'h0733C0;
                5'd19: alarm_glyph = 24'h1C30E0;
                5'd20: alarm_glyph = 24'h383070;
                5'd21: alarm_glyph = 24'h20F030;
                5'd22: alarm_glyph = 24'h00C000;
                default: alarm_glyph = 24'h000000;
            endcase
            3'd1: case (row)   // 急
                5'd1: alarm_glyph = 24'h008000;
                5'd2: alarm_glyph = 24'h01C000;
                5'd3: alarm_glyph = 24'h018000;
                5'd4: alarm_glyph = 24'h03FFC0;
                5'd5: alarm_glyph = 24'h070180;
                5'd6: alarm_glyph = 24'h0E0300;
                5'd7: alarm_glyph = 24'h1FFFF0;
                5'd8: alarm_glyph = 24'h37FFF0;
                5'd9: alarm_glyph = 24'h000030;
                5'd10: alarm_glyph = 24'h040030;
                5'd11: alarm_glyph = 24'h0FFFF0;
                5'd12: alarm_glyph = 24'h000030;
                5'd13: alarm_glyph = 24'h000030;
                5'd14: alarm_glyph = 24'h0FFFF0;
                5'd16: alarm_glyph = 24'h019830;
                5'd17: alarm_glyph = 24'h198C38;
                5'd18: alarm_glyph = 24'h198C1C;
                5'd19: alarm_glyph = 24'h3180EE;
                5'd20: alarm_glyph = 24'h3180C4;
                5'd21: alarm_glyph = 24'h61FFC0;
                5'd22: alarm_glyph = 24'h00FF80;
                default: alarm_glyph = 24'h000000;
            endcase
            3'd2: case (row)   // 疏
                5'd1: alarm_glyph = 24'h000300;
                5'd2: alarm_glyph = 24'h3F8300;
                5'd3: alarm_glyph = 24'h3FFFFC;
                5'd4: alarm_glyph = 24'h033FFC;
                5'd5: alarm_glyph = 24'h060600;
                5'd6: alarm_glyph = 24'h060E20;
                5'd7: alarm_glyph = 24'h060C30;
                5'd8: alarm_glyph = 24'h261838;
                5'd9: alarm_glyph = 24'h363FFC;
                5'd10: alarm_glyph = 24'h37BC0C;
                5'd11: alarm_glyph = 24'h378000;
                5'd12: alarm_glyph = 24'h361B30;
                5'd13: alarm_glyph = 24'h361B30;
                5'd14: alarm_glyph = 24'h361320;
                5'd15: alarm_glyph = 24'h361320;
                5'd16: alarm_glyph = 24'h36B320;
                5'd17: alarm_glyph = 24'h3FB320;
                5'd18: alarm_glyph = 24'h7E3326;
                5'd19: alarm_glyph = 24'h706336;
                5'd20: alarm_glyph = 24'h00633E;
                5'd21: alarm_glyph = 24'h00C31C;
                default: alarm_glyph = 24'h000000;
            endcase
            3'd3: case (row)   // 散
                5'd1: alarm_glyph = 24'h0CC1C0;
                5'd2: alarm_glyph = 24'h0CC180;
                5'd3: alarm_glyph = 24'h0CC180;
                5'd4: alarm_glyph = 24'h3FF100;
                5'd5: alarm_glyph = 24'h0CC3FE;
                5'd6: alarm_glyph = 24'h0CC3FE;
                5'd7: alarm_glyph = 24'h7FF718;
                5'd8: alarm_glyph = 24'h7FF710;
                5'd9: alarm_glyph = 24'h000F10;
                5'd10: alarm_glyph = 24'h1FEF30;
                5'd11: alarm_glyph = 24'h1FE330;
                5'd12: alarm_glyph = 24'h186130;
                5'd13: alarm_glyph = 24'h1FE1B0;
                5'd14: alarm_glyph = 24'h1FE1F0;
                5'd15: alarm_glyph = 24'h1860E0;
                5'd16: alarm_glyph = 24'h1860E0;
                5'd17: alarm_glyph = 24'h1FE0E0;
                5'd18: alarm_glyph = 24'h1861B0;
                5'd19: alarm_glyph = 24'h18631C;
                5'd20: alarm_glyph = 24'h18EE0E;
                5'd21: alarm_glyph = 24'h18CC04;
                default: alarm_glyph = 24'h000000;
            endcase
            3'd4: case (row)   // 火
                5'd1: alarm_glyph = 24'h001800;
                5'd2: alarm_glyph = 24'h001800;
                5'd3: alarm_glyph = 24'h001800;
                5'd4: alarm_glyph = 24'h001800;
                5'd5: alarm_glyph = 24'h001800;
                5'd6: alarm_glyph = 24'h061830;
                5'd7: alarm_glyph = 24'h0E1830;
                5'd8: alarm_glyph = 24'h0C1860;
                5'd9: alarm_glyph = 24'h0C3860;
                5'd10: alarm_glyph = 24'h0C38E0;
                5'd11: alarm_glyph = 24'h1838C0;
                5'd12: alarm_glyph = 24'h083C00;
                5'd13: alarm_glyph = 24'h003C00;
                5'd14: alarm_glyph = 24'h006600;
                5'd15: alarm_glyph = 24'h006600;
                5'd16: alarm_glyph = 24'h00C300;
                5'd17: alarm_glyph = 24'h01C380;
                5'd18: alarm_glyph = 24'h0381C0;
                5'd19: alarm_glyph = 24'h0700F0;
                5'd20: alarm_glyph = 24'h1E007E;
                5'd21: alarm_glyph = 24'h7C001E;
                5'd22: alarm_glyph = 24'h300004;
                default: alarm_glyph = 24'h000000;
            endcase
            3'd5: case (row)   // 警
                5'd0: alarm_glyph = 24'h046080;
                5'd1: alarm_glyph = 24'h066180;
                5'd2: alarm_glyph = 24'h3FFBFE;
                5'd3: alarm_glyph = 24'h0667FE;
                5'd4: alarm_glyph = 24'h0E2618;
                5'd5: alarm_glyph = 24'h1FFB30;
                5'd6: alarm_glyph = 24'h3819B0;
                5'd7: alarm_glyph = 24'h7F98F0;
                5'd8: alarm_glyph = 24'h19B8F0;
                5'd9: alarm_glyph = 24'h1FB3FE;
                5'd10: alarm_glyph = 24'h1F9B0C;
                5'd11: alarm_glyph = 24'h7FFFFE;
                5'd12: alarm_glyph = 24'h7FFFFE;
                5'd13: alarm_glyph = 24'h040020;
                5'd14: alarm_glyph = 24'h07FFE0;
                5'd16: alarm_glyph = 24'h07FFE0;
                5'd18: alarm_glyph = 24'h07FFF0;
                5'd19: alarm_glyph = 24'h040020;
                5'd20: alarm_glyph = 24'h07FFE0;
                5'd21: alarm_glyph = 24'h07FFF0;
                5'd22: alarm_glyph = 24'h040020;
                default: alarm_glyph = 24'h000000;
            endcase
            3'd6: case (row)   // 出
                5'd1: alarm_glyph = 24'h001800;
                5'd2: alarm_glyph = 24'h001800;
                5'd3: alarm_glyph = 24'h0C1830;
                5'd4: alarm_glyph = 24'h0C1830;
                5'd5: alarm_glyph = 24'h0C1830;
                5'd6: alarm_glyph = 24'h0C1830;
                5'd7: alarm_glyph = 24'h0C1830;
                5'd8: alarm_glyph = 24'h0C1830;
                5'd9: alarm_glyph = 24'h0FFFF0;
                5'd10: alarm_glyph = 24'h0FFFF0;
                5'd11: alarm_glyph = 24'h001800;
                5'd12: alarm_glyph = 24'h001800;
                5'd13: alarm_glyph = 24'h181818;
                5'd14: alarm_glyph = 24'h101818;
                5'd15: alarm_glyph = 24'h101818;
                5'd16: alarm_glyph = 24'h101818;
                5'd17: alarm_glyph = 24'h101818;
                5'd18: alarm_glyph = 24'h101818;
                5'd19: alarm_glyph = 24'h1FFFF8;
                5'd20: alarm_glyph = 24'h1FFFF8;
                5'd21: alarm_glyph = 24'h000018;
                5'd22: alarm_glyph = 24'h000008;
                default: alarm_glyph = 24'h000000;
            endcase
            3'd7: case (row)   // 口
                5'd3: alarm_glyph = 24'h0FFFF0;
                5'd4: alarm_glyph = 24'h0FFFF0;
                5'd5: alarm_glyph = 24'h0C0030;
                5'd6: alarm_glyph = 24'h0C0030;
                5'd7: alarm_glyph = 24'h0C0030;
                5'd8: alarm_glyph = 24'h0C0030;
                5'd9: alarm_glyph = 24'h0C0030;
                5'd10: alarm_glyph = 24'h0C0030;
                5'd11: alarm_glyph = 24'h0C0030;
                5'd12: alarm_glyph = 24'h0C0030;
                5'd13: alarm_glyph = 24'h0C0030;
                5'd14: alarm_glyph = 24'h0C0030;
                5'd15: alarm_glyph = 24'h0C0030;
                5'd16: alarm_glyph = 24'h0C0030;
                5'd17: alarm_glyph = 24'h0FFFF0;
                5'd18: alarm_glyph = 24'h0FFFF0;
                5'd19: alarm_glyph = 24'h0C0030;
                5'd20: alarm_glyph = 24'h080010;
                default: alarm_glyph = 24'h000000;
            endcase
            default: alarm_glyph = 24'h000000;
        endcase
    end
endfunction
