// Generated by tools/gen_marquee_ascii_font.py -- DO NOT EDIT BY HAND.
// Re-run the generator instead; tools/check_marquee_ascii_transcription.py
// compares this file against a fresh render, bit for bit.
//
// Included from inside marquee_overlay.v's module body, so this file holds
// a bare function and must NOT be added to the .al file list.
//
// Charset   : printable ASCII 0x20..0x7E (96 glyphs); outer default is blank
//             so any control/DEL byte on the wire can never light a glyph.
// Font      : C:/Windows/Fonts/verdanab.ttf @ 11 px, threshold 128
// Box       : 12 x 12 px; marquee_overlay scales by 2 into the 24x24 cell,
//             addressing gcol[4:1] / row[4:1] -- free bit slices, no divider.
// Bit order : bit 11 is the leftmost column of the row (osd_overlay's
//             font8x8 convention); row 0 is the top.
// Blank rows are folded into the inner default arm to keep the file short.
// Lit row-words: 697 of 1140.

function [11:0] ascii_glyph;
    input [6:0] char_code;
    input [3:0] row;
    begin
        case (char_code)
            7'h20: case (row)   // (space)
                default: ascii_glyph = 12'h000;
            endcase
            7'h21: case (row)   // !
                4'd2: ascii_glyph = 12'h060;
                4'd3: ascii_glyph = 12'h060;
                4'd4: ascii_glyph = 12'h060;
                4'd5: ascii_glyph = 12'h060;
                4'd6: ascii_glyph = 12'h060;
                4'd7: ascii_glyph = 12'h060;
                4'd9: ascii_glyph = 12'h060;
                default: ascii_glyph = 12'h000;
            endcase
            7'h22: case (row)   // "
                4'd4: ascii_glyph = 12'h1B0;
                4'd5: ascii_glyph = 12'h1A0;
                4'd6: ascii_glyph = 12'h120;
                default: ascii_glyph = 12'h000;
            endcase
            7'h23: case (row)   // #
                4'd2: ascii_glyph = 12'h058;
                4'd3: ascii_glyph = 12'h0D0;
                4'd4: ascii_glyph = 12'h3FC;
                4'd5: ascii_glyph = 12'h090;
                4'd6: ascii_glyph = 12'h0B0;
                4'd7: ascii_glyph = 12'h3F8;
                4'd8: ascii_glyph = 12'h120;
                4'd9: ascii_glyph = 12'h120;
                default: ascii_glyph = 12'h000;
            endcase
            7'h24: case (row)   // $
                4'd0: ascii_glyph = 12'h040;
                4'd1: ascii_glyph = 12'h040;
                4'd2: ascii_glyph = 12'h0F0;
                4'd3: ascii_glyph = 12'h1C8;
                4'd4: ascii_glyph = 12'h1E0;
                4'd5: ascii_glyph = 12'h0F8;
                4'd6: ascii_glyph = 12'h078;
                4'd7: ascii_glyph = 12'h158;
                4'd8: ascii_glyph = 12'h1F0;
                4'd9: ascii_glyph = 12'h040;
                4'd10: ascii_glyph = 12'h040;
                default: ascii_glyph = 12'h000;
            endcase
            7'h25: case (row)   // %
                4'd2: ascii_glyph = 12'h718;
                4'd3: ascii_glyph = 12'hD10;
                4'd4: ascii_glyph = 12'h9B0;
                4'd5: ascii_glyph = 12'hD2E;
                4'd6: ascii_glyph = 12'h74B;
                4'd7: ascii_glyph = 12'h0D9;
                4'd8: ascii_glyph = 12'h08B;
                4'd9: ascii_glyph = 12'h18E;
                default: ascii_glyph = 12'h000;
            endcase
            7'h26: case (row)   // &
                4'd2: ascii_glyph = 12'h1E0;
                4'd3: ascii_glyph = 12'h370;
                4'd4: ascii_glyph = 12'h3E0;
                4'd5: ascii_glyph = 12'h1D8;
                4'd6: ascii_glyph = 12'h3F8;
                4'd7: ascii_glyph = 12'h378;
                4'd8: ascii_glyph = 12'h338;
                4'd9: ascii_glyph = 12'h1FC;
                default: ascii_glyph = 12'h000;
            endcase
            7'h27: case (row)   // '
                4'd4: ascii_glyph = 12'h060;
                4'd5: ascii_glyph = 12'h060;
                4'd6: ascii_glyph = 12'h040;
                default: ascii_glyph = 12'h000;
            endcase
            7'h28: case (row)   // (
                4'd0: ascii_glyph = 12'h030;
                4'd1: ascii_glyph = 12'h060;
                4'd2: ascii_glyph = 12'h040;
                4'd3: ascii_glyph = 12'h0C0;
                4'd4: ascii_glyph = 12'h0C0;
                4'd5: ascii_glyph = 12'h0C0;
                4'd6: ascii_glyph = 12'h0C0;
                4'd7: ascii_glyph = 12'h0C0;
                4'd8: ascii_glyph = 12'h040;
                4'd9: ascii_glyph = 12'h060;
                4'd10: ascii_glyph = 12'h030;
                default: ascii_glyph = 12'h000;
            endcase
            7'h29: case (row)   // )
                4'd0: ascii_glyph = 12'h0C0;
                4'd1: ascii_glyph = 12'h060;
                4'd2: ascii_glyph = 12'h020;
                4'd3: ascii_glyph = 12'h030;
                4'd4: ascii_glyph = 12'h030;
                4'd5: ascii_glyph = 12'h030;
                4'd6: ascii_glyph = 12'h030;
                4'd7: ascii_glyph = 12'h030;
                4'd8: ascii_glyph = 12'h020;
                4'd9: ascii_glyph = 12'h060;
                4'd10: ascii_glyph = 12'h0C0;
                default: ascii_glyph = 12'h000;
            endcase
            7'h2A: case (row)   // *
                4'd3: ascii_glyph = 12'h040;
                4'd4: ascii_glyph = 12'h150;
                4'd5: ascii_glyph = 12'h0E0;
                4'd6: ascii_glyph = 12'h150;
                4'd7: ascii_glyph = 12'h040;
                default: ascii_glyph = 12'h000;
            endcase
            7'h2B: case (row)   // +
                4'd2: ascii_glyph = 12'h040;
                4'd3: ascii_glyph = 12'h040;
                4'd4: ascii_glyph = 12'h040;
                4'd5: ascii_glyph = 12'h3F8;
                4'd6: ascii_glyph = 12'h040;
                4'd7: ascii_glyph = 12'h040;
                4'd8: ascii_glyph = 12'h040;
                default: ascii_glyph = 12'h000;
            endcase
            7'h2C: case (row)   // ,
                4'd4: ascii_glyph = 12'h060;
                4'd5: ascii_glyph = 12'h060;
                4'd6: ascii_glyph = 12'h040;
                4'd7: ascii_glyph = 12'h0C0;
                default: ascii_glyph = 12'h000;
            endcase
            7'h2D: case (row)   // -
                4'd5: ascii_glyph = 12'h0F0;
                default: ascii_glyph = 12'h000;
            endcase
            7'h2E: case (row)   // .
                4'd5: ascii_glyph = 12'h060;
                4'd6: ascii_glyph = 12'h060;
                default: ascii_glyph = 12'h000;
            endcase
            7'h2F: case (row)   // /
                4'd0: ascii_glyph = 12'h010;
                4'd1: ascii_glyph = 12'h030;
                4'd2: ascii_glyph = 12'h030;
                4'd3: ascii_glyph = 12'h020;
                4'd4: ascii_glyph = 12'h060;
                4'd5: ascii_glyph = 12'h040;
                4'd6: ascii_glyph = 12'h0C0;
                4'd7: ascii_glyph = 12'h0C0;
                4'd8: ascii_glyph = 12'h080;
                4'd9: ascii_glyph = 12'h180;
                4'd10: ascii_glyph = 12'h100;
                default: ascii_glyph = 12'h000;
            endcase
            7'h30: case (row)   // 0
                4'd2: ascii_glyph = 12'h0F0;
                4'd3: ascii_glyph = 12'h198;
                4'd4: ascii_glyph = 12'h198;
                4'd5: ascii_glyph = 12'h198;
                4'd6: ascii_glyph = 12'h198;
                4'd7: ascii_glyph = 12'h198;
                4'd8: ascii_glyph = 12'h198;
                4'd9: ascii_glyph = 12'h0F0;
                default: ascii_glyph = 12'h000;
            endcase
            7'h31: case (row)   // 1
                4'd2: ascii_glyph = 12'h060;
                4'd3: ascii_glyph = 12'h1E0;
                4'd4: ascii_glyph = 12'h060;
                4'd5: ascii_glyph = 12'h060;
                4'd6: ascii_glyph = 12'h060;
                4'd7: ascii_glyph = 12'h060;
                4'd8: ascii_glyph = 12'h060;
                4'd9: ascii_glyph = 12'h1F8;
                default: ascii_glyph = 12'h000;
            endcase
            7'h32: case (row)   // 2
                4'd2: ascii_glyph = 12'h1F0;
                4'd3: ascii_glyph = 12'h138;
                4'd4: ascii_glyph = 12'h018;
                4'd5: ascii_glyph = 12'h038;
                4'd6: ascii_glyph = 12'h030;
                4'd7: ascii_glyph = 12'h060;
                4'd8: ascii_glyph = 12'h0C0;
                4'd9: ascii_glyph = 12'h1F8;
                default: ascii_glyph = 12'h000;
            endcase
            7'h33: case (row)   // 3
                4'd2: ascii_glyph = 12'h1F0;
                4'd3: ascii_glyph = 12'h118;
                4'd4: ascii_glyph = 12'h018;
                4'd5: ascii_glyph = 12'h070;
                4'd6: ascii_glyph = 12'h018;
                4'd7: ascii_glyph = 12'h018;
                4'd8: ascii_glyph = 12'h118;
                4'd9: ascii_glyph = 12'h1F0;
                default: ascii_glyph = 12'h000;
            endcase
            7'h34: case (row)   // 4
                4'd2: ascii_glyph = 12'h030;
                4'd3: ascii_glyph = 12'h070;
                4'd4: ascii_glyph = 12'h0F0;
                4'd5: ascii_glyph = 12'h0B0;
                4'd6: ascii_glyph = 12'h130;
                4'd7: ascii_glyph = 12'h3F8;
                4'd8: ascii_glyph = 12'h030;
                4'd9: ascii_glyph = 12'h030;
                default: ascii_glyph = 12'h000;
            endcase
            7'h35: case (row)   // 5
                4'd2: ascii_glyph = 12'h1F8;
                4'd3: ascii_glyph = 12'h180;
                4'd4: ascii_glyph = 12'h180;
                4'd5: ascii_glyph = 12'h1F0;
                4'd6: ascii_glyph = 12'h018;
                4'd7: ascii_glyph = 12'h018;
                4'd8: ascii_glyph = 12'h118;
                4'd9: ascii_glyph = 12'h1F0;
                default: ascii_glyph = 12'h000;
            endcase
            7'h36: case (row)   // 6
                4'd2: ascii_glyph = 12'h078;
                4'd3: ascii_glyph = 12'h0C0;
                4'd4: ascii_glyph = 12'h180;
                4'd5: ascii_glyph = 12'h1F0;
                4'd6: ascii_glyph = 12'h198;
                4'd7: ascii_glyph = 12'h198;
                4'd8: ascii_glyph = 12'h198;
                4'd9: ascii_glyph = 12'h0F0;
                default: ascii_glyph = 12'h000;
            endcase
            7'h37: case (row)   // 7
                4'd2: ascii_glyph = 12'h1F8;
                4'd3: ascii_glyph = 12'h018;
                4'd4: ascii_glyph = 12'h030;
                4'd5: ascii_glyph = 12'h030;
                4'd6: ascii_glyph = 12'h060;
                4'd7: ascii_glyph = 12'h060;
                4'd8: ascii_glyph = 12'h0C0;
                4'd9: ascii_glyph = 12'h1C0;
                default: ascii_glyph = 12'h000;
            endcase
            7'h38: case (row)   // 8
                4'd2: ascii_glyph = 12'h0F0;
                4'd3: ascii_glyph = 12'h198;
                4'd4: ascii_glyph = 12'h198;
                4'd5: ascii_glyph = 12'h1F0;
                4'd6: ascii_glyph = 12'h198;
                4'd7: ascii_glyph = 12'h198;
                4'd8: ascii_glyph = 12'h198;
                4'd9: ascii_glyph = 12'h0F0;
                default: ascii_glyph = 12'h000;
            endcase
            7'h39: case (row)   // 9
                4'd2: ascii_glyph = 12'h0F0;
                4'd3: ascii_glyph = 12'h198;
                4'd4: ascii_glyph = 12'h198;
                4'd5: ascii_glyph = 12'h198;
                4'd6: ascii_glyph = 12'h0F8;
                4'd7: ascii_glyph = 12'h018;
                4'd8: ascii_glyph = 12'h030;
                4'd9: ascii_glyph = 12'h1E0;
                default: ascii_glyph = 12'h000;
            endcase
            7'h3A: case (row)   // :
                4'd3: ascii_glyph = 12'h060;
                4'd4: ascii_glyph = 12'h060;
                4'd7: ascii_glyph = 12'h060;
                4'd8: ascii_glyph = 12'h060;
                default: ascii_glyph = 12'h000;
            endcase
            7'h3B: case (row)   // ;
                4'd2: ascii_glyph = 12'h060;
                4'd3: ascii_glyph = 12'h060;
                4'd6: ascii_glyph = 12'h060;
                4'd7: ascii_glyph = 12'h060;
                4'd8: ascii_glyph = 12'h040;
                4'd9: ascii_glyph = 12'h040;
                default: ascii_glyph = 12'h000;
            endcase
            7'h3C: case (row)   // <
                4'd2: ascii_glyph = 12'h008;
                4'd3: ascii_glyph = 12'h038;
                4'd4: ascii_glyph = 12'h1E0;
                4'd5: ascii_glyph = 12'h380;
                4'd6: ascii_glyph = 12'h1E0;
                4'd7: ascii_glyph = 12'h038;
                4'd8: ascii_glyph = 12'h008;
                default: ascii_glyph = 12'h000;
            endcase
            7'h3D: case (row)   // =
                4'd4: ascii_glyph = 12'h3F8;
                4'd7: ascii_glyph = 12'h3F8;
                default: ascii_glyph = 12'h000;
            endcase
            7'h3E: case (row)   // >
                4'd2: ascii_glyph = 12'h200;
                4'd3: ascii_glyph = 12'h1C0;
                4'd4: ascii_glyph = 12'h070;
                4'd5: ascii_glyph = 12'h018;
                4'd6: ascii_glyph = 12'h070;
                4'd7: ascii_glyph = 12'h1C0;
                4'd8: ascii_glyph = 12'h200;
                default: ascii_glyph = 12'h000;
            endcase
            7'h3F: case (row)   // ?
                4'd2: ascii_glyph = 12'h1E0;
                4'd3: ascii_glyph = 12'h130;
                4'd4: ascii_glyph = 12'h030;
                4'd5: ascii_glyph = 12'h070;
                4'd6: ascii_glyph = 12'h0E0;
                4'd7: ascii_glyph = 12'h0C0;
                4'd9: ascii_glyph = 12'h0C0;
                default: ascii_glyph = 12'h000;
            endcase
            7'h40: case (row)   // @
                4'd1: ascii_glyph = 12'h1E0;
                4'd2: ascii_glyph = 12'h318;
                4'd3: ascii_glyph = 12'h6E8;
                4'd4: ascii_glyph = 12'h5A4;
                4'd5: ascii_glyph = 12'h524;
                4'd6: ascii_glyph = 12'h524;
                4'd7: ascii_glyph = 12'h6F8;
                4'd8: ascii_glyph = 12'h300;
                4'd9: ascii_glyph = 12'h1E0;
                default: ascii_glyph = 12'h000;
            endcase
            7'h41: case (row)   // A
                4'd2: ascii_glyph = 12'h070;
                4'd3: ascii_glyph = 12'h070;
                4'd4: ascii_glyph = 12'h0F0;
                4'd5: ascii_glyph = 12'h0D8;
                4'd6: ascii_glyph = 12'h198;
                4'd7: ascii_glyph = 12'h1F8;
                4'd8: ascii_glyph = 12'h18C;
                4'd9: ascii_glyph = 12'h30C;
                default: ascii_glyph = 12'h000;
            endcase
            7'h42: case (row)   // B
                4'd2: ascii_glyph = 12'h3F0;
                4'd3: ascii_glyph = 12'h330;
                4'd4: ascii_glyph = 12'h330;
                4'd5: ascii_glyph = 12'h3F0;
                4'd6: ascii_glyph = 12'h338;
                4'd7: ascii_glyph = 12'h318;
                4'd8: ascii_glyph = 12'h338;
                4'd9: ascii_glyph = 12'h3F0;
                default: ascii_glyph = 12'h000;
            endcase
            7'h43: case (row)   // C
                4'd2: ascii_glyph = 12'h078;
                4'd3: ascii_glyph = 12'h1C8;
                4'd4: ascii_glyph = 12'h180;
                4'd5: ascii_glyph = 12'h180;
                4'd6: ascii_glyph = 12'h180;
                4'd7: ascii_glyph = 12'h180;
                4'd8: ascii_glyph = 12'h1C0;
                4'd9: ascii_glyph = 12'h0F8;
                default: ascii_glyph = 12'h000;
            endcase
            7'h44: case (row)   // D
                4'd2: ascii_glyph = 12'h3E0;
                4'd3: ascii_glyph = 12'h338;
                4'd4: ascii_glyph = 12'h318;
                4'd5: ascii_glyph = 12'h31C;
                4'd6: ascii_glyph = 12'h31C;
                4'd7: ascii_glyph = 12'h318;
                4'd8: ascii_glyph = 12'h338;
                4'd9: ascii_glyph = 12'h3E0;
                default: ascii_glyph = 12'h000;
            endcase
            7'h45: case (row)   // E
                4'd2: ascii_glyph = 12'h1F8;
                4'd3: ascii_glyph = 12'h180;
                4'd4: ascii_glyph = 12'h180;
                4'd5: ascii_glyph = 12'h1F8;
                4'd6: ascii_glyph = 12'h180;
                4'd7: ascii_glyph = 12'h180;
                4'd8: ascii_glyph = 12'h180;
                4'd9: ascii_glyph = 12'h1F8;
                default: ascii_glyph = 12'h000;
            endcase
            7'h46: case (row)   // F
                4'd2: ascii_glyph = 12'h1F8;
                4'd3: ascii_glyph = 12'h180;
                4'd4: ascii_glyph = 12'h180;
                4'd5: ascii_glyph = 12'h1F0;
                4'd6: ascii_glyph = 12'h180;
                4'd7: ascii_glyph = 12'h180;
                4'd8: ascii_glyph = 12'h180;
                4'd9: ascii_glyph = 12'h180;
                default: ascii_glyph = 12'h000;
            endcase
            7'h47: case (row)   // G
                4'd2: ascii_glyph = 12'h0F8;
                4'd3: ascii_glyph = 12'h388;
                4'd4: ascii_glyph = 12'h300;
                4'd5: ascii_glyph = 12'h300;
                4'd6: ascii_glyph = 12'h378;
                4'd7: ascii_glyph = 12'h318;
                4'd8: ascii_glyph = 12'h398;
                4'd9: ascii_glyph = 12'h0F8;
                default: ascii_glyph = 12'h000;
            endcase
            7'h48: case (row)   // H
                4'd2: ascii_glyph = 12'h318;
                4'd3: ascii_glyph = 12'h318;
                4'd4: ascii_glyph = 12'h318;
                4'd5: ascii_glyph = 12'h3F8;
                4'd6: ascii_glyph = 12'h318;
                4'd7: ascii_glyph = 12'h318;
                4'd8: ascii_glyph = 12'h318;
                4'd9: ascii_glyph = 12'h318;
                default: ascii_glyph = 12'h000;
            endcase
            7'h49: case (row)   // I
                4'd2: ascii_glyph = 12'h0F0;
                4'd3: ascii_glyph = 12'h060;
                4'd4: ascii_glyph = 12'h060;
                4'd5: ascii_glyph = 12'h060;
                4'd6: ascii_glyph = 12'h060;
                4'd7: ascii_glyph = 12'h060;
                4'd8: ascii_glyph = 12'h060;
                4'd9: ascii_glyph = 12'h0F0;
                default: ascii_glyph = 12'h000;
            endcase
            7'h4A: case (row)   // J
                4'd2: ascii_glyph = 12'h0F0;
                4'd3: ascii_glyph = 12'h030;
                4'd4: ascii_glyph = 12'h030;
                4'd5: ascii_glyph = 12'h030;
                4'd6: ascii_glyph = 12'h030;
                4'd7: ascii_glyph = 12'h030;
                4'd8: ascii_glyph = 12'h030;
                4'd9: ascii_glyph = 12'h1E0;
                default: ascii_glyph = 12'h000;
            endcase
            7'h4B: case (row)   // K
                4'd2: ascii_glyph = 12'h318;
                4'd3: ascii_glyph = 12'h330;
                4'd4: ascii_glyph = 12'h360;
                4'd5: ascii_glyph = 12'h3C0;
                4'd6: ascii_glyph = 12'h3E0;
                4'd7: ascii_glyph = 12'h370;
                4'd8: ascii_glyph = 12'h330;
                4'd9: ascii_glyph = 12'h318;
                default: ascii_glyph = 12'h000;
            endcase
            7'h4C: case (row)   // L
                4'd2: ascii_glyph = 12'h180;
                4'd3: ascii_glyph = 12'h180;
                4'd4: ascii_glyph = 12'h180;
                4'd5: ascii_glyph = 12'h180;
                4'd6: ascii_glyph = 12'h180;
                4'd7: ascii_glyph = 12'h180;
                4'd8: ascii_glyph = 12'h180;
                4'd9: ascii_glyph = 12'h1F8;
                default: ascii_glyph = 12'h000;
            endcase
            7'h4D: case (row)   // M
                4'd2: ascii_glyph = 12'h38C;
                4'd3: ascii_glyph = 12'h39C;
                4'd4: ascii_glyph = 12'h3DC;
                4'd5: ascii_glyph = 12'h3FC;
                4'd6: ascii_glyph = 12'h37C;
                4'd7: ascii_glyph = 12'h36C;
                4'd8: ascii_glyph = 12'h30C;
                4'd9: ascii_glyph = 12'h30C;
                default: ascii_glyph = 12'h000;
            endcase
            7'h4E: case (row)   // N
                4'd2: ascii_glyph = 12'h398;
                4'd3: ascii_glyph = 12'h398;
                4'd4: ascii_glyph = 12'h3D8;
                4'd5: ascii_glyph = 12'h378;
                4'd6: ascii_glyph = 12'h378;
                4'd7: ascii_glyph = 12'h338;
                4'd8: ascii_glyph = 12'h338;
                4'd9: ascii_glyph = 12'h318;
                default: ascii_glyph = 12'h000;
            endcase
            7'h4F: case (row)   // O
                4'd2: ascii_glyph = 12'h1F0;
                4'd3: ascii_glyph = 12'h398;
                4'd4: ascii_glyph = 12'h31C;
                4'd5: ascii_glyph = 12'h30C;
                4'd6: ascii_glyph = 12'h30C;
                4'd7: ascii_glyph = 12'h31C;
                4'd8: ascii_glyph = 12'h398;
                4'd9: ascii_glyph = 12'h1F0;
                default: ascii_glyph = 12'h000;
            endcase
            7'h50: case (row)   // P
                4'd2: ascii_glyph = 12'h3F0;
                4'd3: ascii_glyph = 12'h330;
                4'd4: ascii_glyph = 12'h338;
                4'd5: ascii_glyph = 12'h330;
                4'd6: ascii_glyph = 12'h3E0;
                4'd7: ascii_glyph = 12'h300;
                4'd8: ascii_glyph = 12'h300;
                4'd9: ascii_glyph = 12'h300;
                default: ascii_glyph = 12'h000;
            endcase
            7'h51: case (row)   // Q
                4'd1: ascii_glyph = 12'h1F0;
                4'd2: ascii_glyph = 12'h398;
                4'd3: ascii_glyph = 12'h31C;
                4'd4: ascii_glyph = 12'h30C;
                4'd5: ascii_glyph = 12'h30C;
                4'd6: ascii_glyph = 12'h31C;
                4'd7: ascii_glyph = 12'h398;
                4'd8: ascii_glyph = 12'h0F0;
                4'd9: ascii_glyph = 12'h070;
                4'd10: ascii_glyph = 12'h03C;
                default: ascii_glyph = 12'h000;
            endcase
            7'h52: case (row)   // R
                4'd2: ascii_glyph = 12'h3F0;
                4'd3: ascii_glyph = 12'h338;
                4'd4: ascii_glyph = 12'h338;
                4'd5: ascii_glyph = 12'h330;
                4'd6: ascii_glyph = 12'h3E0;
                4'd7: ascii_glyph = 12'h370;
                4'd8: ascii_glyph = 12'h338;
                4'd9: ascii_glyph = 12'h318;
                default: ascii_glyph = 12'h000;
            endcase
            7'h53: case (row)   // S
                4'd2: ascii_glyph = 12'h0F8;
                4'd3: ascii_glyph = 12'h188;
                4'd4: ascii_glyph = 12'h180;
                4'd5: ascii_glyph = 12'h1F0;
                4'd6: ascii_glyph = 12'h0F8;
                4'd7: ascii_glyph = 12'h018;
                4'd8: ascii_glyph = 12'h118;
                4'd9: ascii_glyph = 12'h1F0;
                default: ascii_glyph = 12'h000;
            endcase
            7'h54: case (row)   // T
                4'd2: ascii_glyph = 12'h3F8;
                4'd3: ascii_glyph = 12'h060;
                4'd4: ascii_glyph = 12'h060;
                4'd5: ascii_glyph = 12'h060;
                4'd6: ascii_glyph = 12'h060;
                4'd7: ascii_glyph = 12'h060;
                4'd8: ascii_glyph = 12'h060;
                4'd9: ascii_glyph = 12'h060;
                default: ascii_glyph = 12'h000;
            endcase
            7'h55: case (row)   // U
                4'd2: ascii_glyph = 12'h318;
                4'd3: ascii_glyph = 12'h318;
                4'd4: ascii_glyph = 12'h318;
                4'd5: ascii_glyph = 12'h318;
                4'd6: ascii_glyph = 12'h318;
                4'd7: ascii_glyph = 12'h318;
                4'd8: ascii_glyph = 12'h318;
                4'd9: ascii_glyph = 12'h1F0;
                default: ascii_glyph = 12'h000;
            endcase
            7'h56: case (row)   // V
                4'd2: ascii_glyph = 12'h30C;
                4'd3: ascii_glyph = 12'h18C;
                4'd4: ascii_glyph = 12'h198;
                4'd5: ascii_glyph = 12'h198;
                4'd6: ascii_glyph = 12'h0D8;
                4'd7: ascii_glyph = 12'h0F0;
                4'd8: ascii_glyph = 12'h0F0;
                4'd9: ascii_glyph = 12'h070;
                default: ascii_glyph = 12'h000;
            endcase
            7'h57: case (row)   // W
                4'd2: ascii_glyph = 12'hE63;
                4'd3: ascii_glyph = 12'h673;
                4'd4: ascii_glyph = 12'h676;
                4'd5: ascii_glyph = 12'h6F6;
                4'd6: ascii_glyph = 12'h3DE;
                4'd7: ascii_glyph = 12'h39E;
                4'd8: ascii_glyph = 12'h39C;
                4'd9: ascii_glyph = 12'h39C;
                default: ascii_glyph = 12'h000;
            endcase
            7'h58: case (row)   // X
                4'd2: ascii_glyph = 12'h18C;
                4'd3: ascii_glyph = 12'h1D8;
                4'd4: ascii_glyph = 12'h0F0;
                4'd5: ascii_glyph = 12'h070;
                4'd6: ascii_glyph = 12'h070;
                4'd7: ascii_glyph = 12'h0F8;
                4'd8: ascii_glyph = 12'h198;
                4'd9: ascii_glyph = 12'h38C;
                default: ascii_glyph = 12'h000;
            endcase
            7'h59: case (row)   // Y
                4'd2: ascii_glyph = 12'h38C;
                4'd3: ascii_glyph = 12'h198;
                4'd4: ascii_glyph = 12'h0F8;
                4'd5: ascii_glyph = 12'h0F0;
                4'd6: ascii_glyph = 12'h060;
                4'd7: ascii_glyph = 12'h060;
                4'd8: ascii_glyph = 12'h060;
                4'd9: ascii_glyph = 12'h060;
                default: ascii_glyph = 12'h000;
            endcase
            7'h5A: case (row)   // Z
                4'd2: ascii_glyph = 12'h1F8;
                4'd3: ascii_glyph = 12'h038;
                4'd4: ascii_glyph = 12'h078;
                4'd5: ascii_glyph = 12'h0F0;
                4'd6: ascii_glyph = 12'h0E0;
                4'd7: ascii_glyph = 12'h1C0;
                4'd8: ascii_glyph = 12'h380;
                4'd9: ascii_glyph = 12'h3F8;
                default: ascii_glyph = 12'h000;
            endcase
            7'h5B: case (row)   // [
                4'd0: ascii_glyph = 12'h0F0;
                4'd1: ascii_glyph = 12'h0C0;
                4'd2: ascii_glyph = 12'h0C0;
                4'd3: ascii_glyph = 12'h0C0;
                4'd4: ascii_glyph = 12'h0C0;
                4'd5: ascii_glyph = 12'h0C0;
                4'd6: ascii_glyph = 12'h0C0;
                4'd7: ascii_glyph = 12'h0C0;
                4'd8: ascii_glyph = 12'h0C0;
                4'd9: ascii_glyph = 12'h0C0;
                4'd10: ascii_glyph = 12'h0F0;
                default: ascii_glyph = 12'h000;
            endcase
            7'h5C: case (row)   // (backslash)
                4'd0: ascii_glyph = 12'h180;
                4'd1: ascii_glyph = 12'h080;
                4'd2: ascii_glyph = 12'h0C0;
                4'd3: ascii_glyph = 12'h0C0;
                4'd4: ascii_glyph = 12'h040;
                4'd5: ascii_glyph = 12'h060;
                4'd6: ascii_glyph = 12'h020;
                4'd7: ascii_glyph = 12'h030;
                4'd8: ascii_glyph = 12'h030;
                4'd9: ascii_glyph = 12'h010;
                4'd10: ascii_glyph = 12'h018;
                default: ascii_glyph = 12'h000;
            endcase
            7'h5D: case (row)   // ]
                4'd0: ascii_glyph = 12'h0F0;
                4'd1: ascii_glyph = 12'h030;
                4'd2: ascii_glyph = 12'h030;
                4'd3: ascii_glyph = 12'h030;
                4'd4: ascii_glyph = 12'h030;
                4'd5: ascii_glyph = 12'h030;
                4'd6: ascii_glyph = 12'h030;
                4'd7: ascii_glyph = 12'h030;
                4'd8: ascii_glyph = 12'h030;
                4'd9: ascii_glyph = 12'h030;
                4'd10: ascii_glyph = 12'h0F0;
                default: ascii_glyph = 12'h000;
            endcase
            7'h5E: case (row)   // ^
                4'd4: ascii_glyph = 12'h060;
                4'd5: ascii_glyph = 12'h0F0;
                4'd6: ascii_glyph = 12'h190;
                4'd7: ascii_glyph = 12'h318;
                default: ascii_glyph = 12'h000;
            endcase
            7'h5F: case (row)   // _
                4'd5: ascii_glyph = 12'h3FC;
                default: ascii_glyph = 12'h000;
            endcase
            7'h60: case (row)   // `
                4'd5: ascii_glyph = 12'h0C0;
                4'd6: ascii_glyph = 12'h060;
                default: ascii_glyph = 12'h000;
            endcase
            7'h61: case (row)   // a
                4'd3: ascii_glyph = 12'h1F0;
                4'd4: ascii_glyph = 12'h030;
                4'd5: ascii_glyph = 12'h0F0;
                4'd6: ascii_glyph = 12'h190;
                4'd7: ascii_glyph = 12'h1B0;
                4'd8: ascii_glyph = 12'h1F0;
                default: ascii_glyph = 12'h000;
            endcase
            7'h62: case (row)   // b
                4'd1: ascii_glyph = 12'h180;
                4'd2: ascii_glyph = 12'h180;
                4'd3: ascii_glyph = 12'h180;
                4'd4: ascii_glyph = 12'h1F0;
                4'd5: ascii_glyph = 12'h198;
                4'd6: ascii_glyph = 12'h198;
                4'd7: ascii_glyph = 12'h198;
                4'd8: ascii_glyph = 12'h198;
                4'd9: ascii_glyph = 12'h1F0;
                default: ascii_glyph = 12'h000;
            endcase
            7'h63: case (row)   // c
                4'd3: ascii_glyph = 12'h0F0;
                4'd4: ascii_glyph = 12'h180;
                4'd5: ascii_glyph = 12'h180;
                4'd6: ascii_glyph = 12'h180;
                4'd7: ascii_glyph = 12'h180;
                4'd8: ascii_glyph = 12'h0F0;
                default: ascii_glyph = 12'h000;
            endcase
            7'h64: case (row)   // d
                4'd1: ascii_glyph = 12'h018;
                4'd2: ascii_glyph = 12'h018;
                4'd3: ascii_glyph = 12'h018;
                4'd4: ascii_glyph = 12'h0F8;
                4'd5: ascii_glyph = 12'h198;
                4'd6: ascii_glyph = 12'h198;
                4'd7: ascii_glyph = 12'h198;
                4'd8: ascii_glyph = 12'h198;
                4'd9: ascii_glyph = 12'h0F8;
                default: ascii_glyph = 12'h000;
            endcase
            7'h65: case (row)   // e
                4'd3: ascii_glyph = 12'h0F0;
                4'd4: ascii_glyph = 12'h198;
                4'd5: ascii_glyph = 12'h1F8;
                4'd6: ascii_glyph = 12'h180;
                4'd7: ascii_glyph = 12'h188;
                4'd8: ascii_glyph = 12'h0F0;
                default: ascii_glyph = 12'h000;
            endcase
            7'h66: case (row)   // f
                4'd1: ascii_glyph = 12'h070;
                4'd2: ascii_glyph = 12'h0C0;
                4'd3: ascii_glyph = 12'h0C0;
                4'd4: ascii_glyph = 12'h1E0;
                4'd5: ascii_glyph = 12'h0C0;
                4'd6: ascii_glyph = 12'h0C0;
                4'd7: ascii_glyph = 12'h0C0;
                4'd8: ascii_glyph = 12'h0C0;
                4'd9: ascii_glyph = 12'h0C0;
                default: ascii_glyph = 12'h000;
            endcase
            7'h67: case (row)   // g
                4'd2: ascii_glyph = 12'h0F8;
                4'd3: ascii_glyph = 12'h198;
                4'd4: ascii_glyph = 12'h198;
                4'd5: ascii_glyph = 12'h198;
                4'd6: ascii_glyph = 12'h198;
                4'd7: ascii_glyph = 12'h0F8;
                4'd8: ascii_glyph = 12'h030;
                4'd9: ascii_glyph = 12'h1F0;
                default: ascii_glyph = 12'h000;
            endcase
            7'h68: case (row)   // h
                4'd1: ascii_glyph = 12'h180;
                4'd2: ascii_glyph = 12'h180;
                4'd3: ascii_glyph = 12'h180;
                4'd4: ascii_glyph = 12'h1F0;
                4'd5: ascii_glyph = 12'h198;
                4'd6: ascii_glyph = 12'h198;
                4'd7: ascii_glyph = 12'h198;
                4'd8: ascii_glyph = 12'h198;
                4'd9: ascii_glyph = 12'h198;
                default: ascii_glyph = 12'h000;
            endcase
            7'h69: case (row)   // i
                4'd2: ascii_glyph = 12'h060;
                4'd4: ascii_glyph = 12'h060;
                4'd5: ascii_glyph = 12'h060;
                4'd6: ascii_glyph = 12'h060;
                4'd7: ascii_glyph = 12'h060;
                4'd8: ascii_glyph = 12'h060;
                4'd9: ascii_glyph = 12'h060;
                default: ascii_glyph = 12'h000;
            endcase
            7'h6A: case (row)   // j
                4'd1: ascii_glyph = 12'h070;
                4'd3: ascii_glyph = 12'h0F0;
                4'd4: ascii_glyph = 12'h030;
                4'd5: ascii_glyph = 12'h030;
                4'd6: ascii_glyph = 12'h030;
                4'd7: ascii_glyph = 12'h030;
                4'd8: ascii_glyph = 12'h030;
                4'd9: ascii_glyph = 12'h060;
                4'd10: ascii_glyph = 12'h0E0;
                default: ascii_glyph = 12'h000;
            endcase
            7'h6B: case (row)   // k
                4'd1: ascii_glyph = 12'h180;
                4'd2: ascii_glyph = 12'h180;
                4'd3: ascii_glyph = 12'h180;
                4'd4: ascii_glyph = 12'h198;
                4'd5: ascii_glyph = 12'h1B0;
                4'd6: ascii_glyph = 12'h1E0;
                4'd7: ascii_glyph = 12'h1F0;
                4'd8: ascii_glyph = 12'h1B0;
                4'd9: ascii_glyph = 12'h198;
                default: ascii_glyph = 12'h000;
            endcase
            7'h6C: case (row)   // l
                4'd1: ascii_glyph = 12'h060;
                4'd2: ascii_glyph = 12'h060;
                4'd3: ascii_glyph = 12'h060;
                4'd4: ascii_glyph = 12'h060;
                4'd5: ascii_glyph = 12'h060;
                4'd6: ascii_glyph = 12'h060;
                4'd7: ascii_glyph = 12'h060;
                4'd8: ascii_glyph = 12'h060;
                4'd9: ascii_glyph = 12'h060;
                default: ascii_glyph = 12'h000;
            endcase
            7'h6D: case (row)   // m
                4'd3: ascii_glyph = 12'h7DC;
                4'd4: ascii_glyph = 12'h666;
                4'd5: ascii_glyph = 12'h666;
                4'd6: ascii_glyph = 12'h666;
                4'd7: ascii_glyph = 12'h666;
                4'd8: ascii_glyph = 12'h666;
                default: ascii_glyph = 12'h000;
            endcase
            7'h6E: case (row)   // n
                4'd3: ascii_glyph = 12'h1F0;
                4'd4: ascii_glyph = 12'h198;
                4'd5: ascii_glyph = 12'h198;
                4'd6: ascii_glyph = 12'h198;
                4'd7: ascii_glyph = 12'h198;
                4'd8: ascii_glyph = 12'h198;
                default: ascii_glyph = 12'h000;
            endcase
            7'h6F: case (row)   // o
                4'd3: ascii_glyph = 12'h0F0;
                4'd4: ascii_glyph = 12'h198;
                4'd5: ascii_glyph = 12'h198;
                4'd6: ascii_glyph = 12'h198;
                4'd7: ascii_glyph = 12'h198;
                4'd8: ascii_glyph = 12'h0F0;
                default: ascii_glyph = 12'h000;
            endcase
            7'h70: case (row)   // p
                4'd2: ascii_glyph = 12'h1F0;
                4'd3: ascii_glyph = 12'h198;
                4'd4: ascii_glyph = 12'h198;
                4'd5: ascii_glyph = 12'h198;
                4'd6: ascii_glyph = 12'h198;
                4'd7: ascii_glyph = 12'h1F0;
                4'd8: ascii_glyph = 12'h180;
                4'd9: ascii_glyph = 12'h180;
                default: ascii_glyph = 12'h000;
            endcase
            7'h71: case (row)   // q
                4'd2: ascii_glyph = 12'h0F8;
                4'd3: ascii_glyph = 12'h198;
                4'd4: ascii_glyph = 12'h198;
                4'd5: ascii_glyph = 12'h198;
                4'd6: ascii_glyph = 12'h198;
                4'd7: ascii_glyph = 12'h0F8;
                4'd8: ascii_glyph = 12'h018;
                4'd9: ascii_glyph = 12'h018;
                default: ascii_glyph = 12'h000;
            endcase
            7'h72: case (row)   // r
                4'd3: ascii_glyph = 12'h0F0;
                4'd4: ascii_glyph = 12'h0F0;
                4'd5: ascii_glyph = 12'h0C0;
                4'd6: ascii_glyph = 12'h0C0;
                4'd7: ascii_glyph = 12'h0C0;
                4'd8: ascii_glyph = 12'h0C0;
                default: ascii_glyph = 12'h000;
            endcase
            7'h73: case (row)   // s
                4'd3: ascii_glyph = 12'h0F0;
                4'd4: ascii_glyph = 12'h180;
                4'd5: ascii_glyph = 12'h1E0;
                4'd6: ascii_glyph = 12'h0F0;
                4'd7: ascii_glyph = 12'h030;
                4'd8: ascii_glyph = 12'h1E0;
                default: ascii_glyph = 12'h000;
            endcase
            7'h74: case (row)   // t
                4'd2: ascii_glyph = 12'h0C0;
                4'd3: ascii_glyph = 12'h0C0;
                4'd4: ascii_glyph = 12'h1F0;
                4'd5: ascii_glyph = 12'h0C0;
                4'd6: ascii_glyph = 12'h0C0;
                4'd7: ascii_glyph = 12'h0C0;
                4'd8: ascii_glyph = 12'h0C0;
                4'd9: ascii_glyph = 12'h070;
                default: ascii_glyph = 12'h000;
            endcase
            7'h75: case (row)   // u
                4'd3: ascii_glyph = 12'h198;
                4'd4: ascii_glyph = 12'h198;
                4'd5: ascii_glyph = 12'h198;
                4'd6: ascii_glyph = 12'h198;
                4'd7: ascii_glyph = 12'h198;
                4'd8: ascii_glyph = 12'h0D8;
                default: ascii_glyph = 12'h000;
            endcase
            7'h76: case (row)   // v
                4'd3: ascii_glyph = 12'h318;
                4'd4: ascii_glyph = 12'h1B0;
                4'd5: ascii_glyph = 12'h1B0;
                4'd6: ascii_glyph = 12'h0F0;
                4'd7: ascii_glyph = 12'h0E0;
                4'd8: ascii_glyph = 12'h0E0;
                default: ascii_glyph = 12'h000;
            endcase
            7'h77: case (row)   // w
                4'd3: ascii_glyph = 12'h666;
                4'd4: ascii_glyph = 12'h376;
                4'd5: ascii_glyph = 12'h376;
                4'd6: ascii_glyph = 12'h3DC;
                4'd7: ascii_glyph = 12'h1DC;
                4'd8: ascii_glyph = 12'h19C;
                default: ascii_glyph = 12'h000;
            endcase
            7'h78: case (row)   // x
                4'd3: ascii_glyph = 12'h198;
                4'd4: ascii_glyph = 12'h1F0;
                4'd5: ascii_glyph = 12'h0E0;
                4'd6: ascii_glyph = 12'h0E0;
                4'd7: ascii_glyph = 12'h1F0;
                4'd8: ascii_glyph = 12'h198;
                default: ascii_glyph = 12'h000;
            endcase
            7'h79: case (row)   // y
                4'd2: ascii_glyph = 12'h318;
                4'd3: ascii_glyph = 12'h1B0;
                4'd4: ascii_glyph = 12'h1B0;
                4'd5: ascii_glyph = 12'h0F0;
                4'd6: ascii_glyph = 12'h0E0;
                4'd7: ascii_glyph = 12'h0E0;
                4'd8: ascii_glyph = 12'h0C0;
                4'd9: ascii_glyph = 12'h0C0;
                default: ascii_glyph = 12'h000;
            endcase
            7'h7A: case (row)   // z
                4'd3: ascii_glyph = 12'h0F8;
                4'd4: ascii_glyph = 12'h038;
                4'd5: ascii_glyph = 12'h070;
                4'd6: ascii_glyph = 12'h060;
                4'd7: ascii_glyph = 12'h0C0;
                4'd8: ascii_glyph = 12'h1F8;
                default: ascii_glyph = 12'h000;
            endcase
            7'h7B: case (row)   // {
                4'd0: ascii_glyph = 12'h038;
                4'd1: ascii_glyph = 12'h060;
                4'd2: ascii_glyph = 12'h060;
                4'd3: ascii_glyph = 12'h060;
                4'd4: ascii_glyph = 12'h040;
                4'd5: ascii_glyph = 12'h180;
                4'd6: ascii_glyph = 12'h040;
                4'd7: ascii_glyph = 12'h060;
                4'd8: ascii_glyph = 12'h060;
                4'd9: ascii_glyph = 12'h060;
                4'd10: ascii_glyph = 12'h038;
                default: ascii_glyph = 12'h000;
            endcase
            7'h7C: case (row)   // |
                4'd0: ascii_glyph = 12'h060;
                4'd1: ascii_glyph = 12'h060;
                4'd2: ascii_glyph = 12'h060;
                4'd3: ascii_glyph = 12'h060;
                4'd4: ascii_glyph = 12'h060;
                4'd5: ascii_glyph = 12'h060;
                4'd6: ascii_glyph = 12'h060;
                4'd7: ascii_glyph = 12'h060;
                4'd8: ascii_glyph = 12'h060;
                4'd9: ascii_glyph = 12'h060;
                4'd10: ascii_glyph = 12'h060;
                default: ascii_glyph = 12'h000;
            endcase
            7'h7D: case (row)   // }
                4'd0: ascii_glyph = 12'h1C0;
                4'd1: ascii_glyph = 12'h060;
                4'd2: ascii_glyph = 12'h060;
                4'd3: ascii_glyph = 12'h060;
                4'd4: ascii_glyph = 12'h020;
                4'd5: ascii_glyph = 12'h038;
                4'd6: ascii_glyph = 12'h020;
                4'd7: ascii_glyph = 12'h060;
                4'd8: ascii_glyph = 12'h060;
                4'd9: ascii_glyph = 12'h060;
                4'd10: ascii_glyph = 12'h1C0;
                default: ascii_glyph = 12'h000;
            endcase
            7'h7E: case (row)   // ~
                4'd4: ascii_glyph = 12'h18C;
                4'd5: ascii_glyph = 12'h34C;
                4'd6: ascii_glyph = 12'h268;
                4'd7: ascii_glyph = 12'h238;
                default: ascii_glyph = 12'h000;
            endcase
            default: ascii_glyph = 12'h000;
        endcase
    end
endfunction
