#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Prove alarm_font.vh is a faithful transcription of the glyph render.

Mirrors tools/check_marquee_transcription.py for the alarm headline table: it
re-imports gen_alarm_font.build_glyphs(), re-renders every glyph from the system
font, and compares the result against the .vh on disk bit for bit. Hand-editing
the .vh, regenerating it with a different font or threshold, or letting the
generator's geometry drift away from alarm_overlay.v's localparams all fail here.

Unlike the marquee checker this one also re-runs the generator's own self-checks,
because alarm_font.vh is new and its negative controls have never been exercised
against a committed file: a check that has only ever passed on the machine that
wrote it is not evidence.

    python tools/check_alarm_font_transcription.py
"""

from __future__ import annotations

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import gen_alarm_font as g  # noqa: E402


def main():
    failures = 0

    def report(label, found):
        nonlocal failures
        for f in found:
            print("  FAIL: " + f)
        failures += len(found)
        if not found:
            print("  pass: " + label)

    if not os.path.exists(g.VH_PATH):
        print("FAIL: %s does not exist; run tools/gen_alarm_font.py" % g.VH_PATH)
        return 1

    print("=== rendering %d glyphs from %s @ %d px, threshold %d"
          % (len(g.GLYPHS), os.path.basename(g.FONT_PATH), g.FONT_SIZE, g.THRESHOLD))
    if not os.path.exists(g.FONT_PATH):
        print("FAIL: font %s is not installed; the .vh cannot be re-derived"
              % g.FONT_PATH)
        return 1

    rendered = g.build_glyphs()
    cells = [rows for rows, _ in rendered]
    infos = [info for _, info in rendered]
    report("no glyph was resampled or clipped",
           [] if not any(i["resampled"] or i["clipped"] for i in infos)
           else ["a glyph was resampled/clipped, which changes what the .vh holds"])

    print("=== self-checks")
    report("glyph table", g.check_font(cells, infos))
    report("generator geometry", g.check_geometry())
    report("RTL message table", g.check_rtl_words())
    report("RTL geometry localparams", g.check_rtl_geometry())
    report("RTL blink wires", g.check_rtl_blink())
    report("RTL mux arm order", g.check_rtl_mux_order())

    print("=== negative controls (the checks above must have teeth)")
    report("negative controls", g.check_negative_controls())

    print("=== .vh on disk against a fresh render")
    with open(g.VH_PATH, "r", encoding="utf-8", errors="replace") as fh:
        text = fh.read()
    expected = g.table_from_cells(cells)
    parsed = g.parse_vh(text)
    diffs = g.tables_equal(parsed, expected)
    if diffs:
        print("  FAIL: %d row(s) differ; first 10:" % len(diffs))
        for d in diffs[:10]:
            print("        " + d)
        failures += 1
    else:
        print("  pass: all %d cells x %d rows identical" % (len(expected), g.CELL))

    # The emitter's own header names the generator and the checker; a stale string
    # here means the file was written by something else.
    if "Generated by tools/gen_alarm_font.py" not in text.splitlines()[0]:
        print("  FAIL: the .vh header does not name gen_alarm_font.py as its source")
        failures += 1

    print("\n%s" % ("FAIL -- %d issue(s)" % failures if failures
                    else "OK -- alarm_font.vh is a faithful transcription"))
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
