#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
sim_emergency.py -- cycle-accurate model of the emergency-takeover path.

Why this exists
---------------
There is no Verilog simulator on this machine (project memory
"no-verilog-simulator-use-python-models"), so the emergency terminal's control
logic is pinned down here, in Python, before any of it goes near a 10-minute TD
build and a hand-flash. This models the exact non-blocking behaviour of the three
clock domains the feature touches:

  * clk (50 MHz)      -- emergency_ctrl: 3FF pin synchronisers, the asymmetric
                         (immediate-set / timed-release) debouncer, the
                         three-candidate priority resolver, the {active,type}
                         state register and its companion toggle, the VOLM latch,
                         and the burn-in sequencer.
                     -- top's merge point: every non-ALRM/VOLM command strobe is
                         ANDed with ~hold while the alarm is up.
  * sd_card_clk       -- hold crosses on a bare 2FF and gates the PHYSICAL
   (100 MHz)            key1/key2 inputs, so the carousel cannot wander under
                         the alarm and resumes on the same picture after release.
  * video_clk         -- hold crosses two ways on purpose:
   (25 MHz)              - active level, bare 2FF  -> audio + buzzer (immediate)
                          - {active,type}, data+toggle -> staging register, then
                            a frame-atomic latch at video_frame_start -> overlay.
                         Plus the 2FF on vol_level and the 4-way audio mux.

Frame timing is generated by a shrinkable divider (FRAME_VCLKS); the real frame
is 800*525 = 420,000 video clocks. The frame-atomic latch is a bare
`if (video_frame_start)` whose correctness does not depend on frame length, so
shrinking it is the same legitimate speed-up sim_uart_ctrl.py applies to
CLKS_PER_BIT -- and Pass A converts the structural result back to milliseconds
from the real geometry. Pass F likewise re-runs the release window at the SHIPPED
CLK_FREQ_HZ / RELEASE_MS so the constant that goes on the board is the one proved.

What it verifies (passes A-I)
-----------------------------
  A. Takeover latency. Sweeping the trigger across every phase of the frame, the
     overlay's frame-atomic output follows the clk-domain decision within
     (one frame + CDC depth) and never takes two. The audio/buzzer path, which
     takes the bare 2FF instead, must be strictly faster -- it has no tearing to
     avoid. Converted to the shipped 16.80 ms/frame number.
  B. Single stage, forced, explicit release. The alarm survives 50 idle frames
     (no timeout -- a self-clearing fire alarm is a liability), ALRM 0 is the only
     command release, a second ALRM n replaces rather than nests, and the release
     lands on exactly one frame boundary.
  C. Command freeze at the merge point. All eleven other commands while the alarm
     is up change NOTHING in the clk latches or the sd/video crossings, and the
     SAME commands with no alarm do change them, so the check is not vacuous.
     ALRM and VOLM stay live -- ALRM is the alarm's own control, VOLM is a user's
     right. Physical key1 is swallowed under the alarm and works without it.
  D. Multi-source fusion and fail-safe release. Three requestors (command, T1
     manual, T2 sensor). Releasing any one must NOT drop the alarm while another
     still asks -- release is an AND, not last-writer-wins. Type priority
     火警(1) > 疏散(2) > 通用(3) is the numeric minimum of the live candidates,
     so escalation can only lower the code, and de-escalation is refused while a
     higher requestor holds. Escalation never re-times the alarm.
  E. Asymmetric debounce. Make arms in a few clk; a 19.99 ms break does not
     clear, a clean one does. NEGATIVE CONTROL: a symmetric debouncer pushes the
     make past one frame, which is exactly the headline property it would break.
  F. Real timing: the shipped 20 ms release window at 50 MHz.
  G. Volume and the siren bypass. VOLM 2/1/0 is a 0/-12 dB/-inf digital gain on
     the two signage sources; the siren bypasses it, because a muted fire alarm
     is worse than no alarm. The alarm select must not appear in audio_valid --
     checked against the shipped RTL text, because audio_arc_calculate counts 48
     valids per CTS and a gap loses HDMI audio lock.
  H. The one-line retreat. EMERGENCY_ENABLE=0 makes the whole System
     indistinguishable from one with no emergency_ctrl, and does so on the DATA
     as well as the strobes -- structural check over the RTL text, because this
     project has already been caught once by a retreat that only gated a strobe
     (led[3]) and so left the instance a load and out of the area report never.
  I. Siren synthesiser arithmetic: 32-bit phase-accumulator frequencies land
     within 1 Hz of target, and the accumulator is advanced, never reloaded, so
     a frequency swap cannot step the waveform.

Honest limits
-------------
  * The pixel CONTENT of alarm_overlay (glyphs, travelling chevrons, hazard
    stripes) is not modelled here. This proves the enable / type / latency /
    gating / CDC contract that FEEDS it. The raster is evidence-backed by
    tools/gen_alarm_font.py's preview PNGs and
    tools/check_alarm_font_transcription.py, the same split marquee_overlay uses.
  * sd_card_bmp's internals (its own key debouncer, the IMGX img_loaded_count
    gate, the carousel second counter) are not modelled end-to-end. Pass C
    proves the values feeding those gates are frozen, which is what a snapshot
    comparison can actually check; `next_press_sd` here stands in for "key1's
    edge reached sd_card_bmp", not for its debounce maths.
  * The siren waveform is modelled as its amplitude/frequency contract, not as
    the full accumulator. What could silently break the build is the valid
    stream, and that is what Pass G measures against the RTL.

Usage
-----
    python tools/sim_emergency.py            # all passes, PASS/FAIL per check
    python tools/sim_emergency.py --verbose
Exit code 0 on success, 1 if any check fails.
"""

import argparse
import os
import re
import sys

# ---------------------------------------------------------------------------
# Clock geometry (ns). Offsets guarantee no two posedges ever coincide, so every
# CDC sample in here is genuinely asynchronous instead of luckily aligned.
# ---------------------------------------------------------------------------
CLK_PERIOD = 20        # 50 MHz
SD_PERIOD = 10         # 100 MHz
VID_PERIOD = 40        # 25 MHz
CLK_OFF = 0
SD_OFF = 3
VID_OFF = 7            # never 0 or 20 mod 40, so video and clk never coincide

FRAME_VCLKS = 200      # shrunken frame; see "Honest limits"
CDC_VCLKS = 4          # 3FF on the toggle + the clock that commits the staging
LEVEL_VCLKS = 2        # bare 2FF feeding the audio/buzzer mux

H_TOTAL = 800
V_TOTAL = 525
PIXEL_CLK_MHZ = 25.0
FRAME_MS = H_TOTAL * V_TOTAL / (PIXEL_CLK_MHZ * 1000.0)      # 16.80 ms

# The debouncer and the burn-in sequencer are pure functions of CLK_FREQ_HZ, so
# passing a smaller ticks-per-ms is the same parameter-shrink argument, and Pass
# F re-runs the shipped value.
TICKS_PER_MS_FAST = 50                  # 1000x shrunk
TICKS_PER_MS_REAL = 50_000              # 50 MHz / 1000

TYPE_NONE, TYPE_FIRE, TYPE_EVAC, TYPE_GEN = 0, 1, 2, 3
TYPE_GENERAL = TYPE_GEN                   # the name alarm_siren.v uses for code 3
VOL_FULL, VOL_MID, VOL_MUTE = 2, 1, 0

MANUAL_TYPE = TYPE_EVAC                 # T1 manual call point orders evacuation
AUTO_TYPE = TYPE_FIRE                   # T2 smoke/heat contact reports a fire

TONE_LEFT = 0x300000
MUS_LEFT = 0x400000
SIREN_LEFT = 0x700000

# Commands that must freeze while the alarm holds. ALRM/VOLM are the deliberate
# exceptions, exercised separately in Pass C.
FREEZE_CMDS = ["NEXT", "AUTO", "BRUP", "BRGT 0", "MODE 3", "MARQ 0", "IMGX 2",
               "FILT 5", "FONT 1", "MUSC 1", "SPED 5"]

# Everything the emergency path is allowed to move, plus the pre-existing latches
# it is not. One comparable tuple, so "frozen" and "retreated" are both equality
# proofs rather than hand-written expectation lists.
STATE_KEYS = ('req_cmd', 'mlvl', 'alvl', 'emg_state', 'emg_tgl', 'vol_level',
              'burn_cnt', 'burn_on', 'burn_type', 'burn_req', 'burn_req_v',
              'brightness', 'mode_ovr_val', 'mode_ovr_en', 'marq_ovr_val',
              'marq_ovr_en', 'filt_val', 'font_val', 'music_en',
              'img_sel_lat', 'speed_lat', 'next_tgl', 'auto_tgl', 'img_tgl',
              'spd_tgl', 'hold_s0', 'hold_sd', 'key1_seen', 'next_press_sd',
              'emg_act_s0', 'emg_act_v1', 'emg_type_s0', 'emg_type_v1',
              'etgl_s0', 'etgl_s1', 'etgl_s2',
              'estg_act', 'estg_type', 'ef_act', 'ef_type',
              'vol_s0', 'vol_v1')

# The signage state that predates the feature. A realistic retreat barrage below
# has to include legitimate NEXT/MODE/BRGT traffic, so the "the feature is gone"
# equality can only be about the rest -- and derived rather than hand-listed, so
# a new register cannot silently fall on the wrong side of the split.
PREEXISTING_KEYS = ('brightness', 'mode_ovr_val', 'mode_ovr_en', 'marq_ovr_val',
                    'marq_ovr_en', 'filt_val', 'font_val', 'music_en',
                    'img_sel_lat', 'speed_lat', 'next_tgl', 'auto_tgl',
                    'img_tgl', 'spd_tgl', 'key1_seen', 'next_press_sd')
EMG_KEYS = tuple(k for k in STATE_KEYS if k not in PREEXISTING_KEYS)


def frame_bytes(cmd_str):
    """Wire bytes of a TJC framed command: ASCII payload + three 0xFF."""
    return [ord(c) for c in cmd_str] + [0xFF, 0xFF, 0xFF]


def parse_cmd(byte_list):
    """
    Stand-in for uart_screen_ctrl's dispatch: framed bytes -> the strobe/value
    pair it fires. A direct transcription of the RTL's guards, so a typo here
    cannot make a check pass that the real parser would reject. Note the two
    invariants this file has to obey rather than invent:

      * the keyword is exactly FOUR payload bytes, because the RTL dispatches on
        `case ({c0, c1, c2, c3})`. That is why the alarm commands are ALRM and
        VOLM rather than the shorter EMG and VOL a reviewer would expect -- a
        three-letter keyword makes clen 5 and no arm of the case matches.
      * payload[4] is the mandatory space and payload[5] the argument digit,
        because the RTL checks `clen == 6 && c4 == " " && <c5 in range>`.

    sim_uart_ctrl.py already proves this parser byte-for-byte against the wire;
    duplicating that proof is not this file's job.
    """
    payload = bytes(b for b in byte_list if b != 0xFF)
    kw = payload[:4].decode('ascii', 'replace')
    clen = len(payload)
    arg = payload[5] if clen == 6 and payload[4] == 0x20 else None
    out = {}

    def digit(lo, hi):
        return arg is not None and lo <= arg <= hi

    if clen == 4:
        for k, cmd in (('NEXT', 'cmd_next_pulse'), ('AUTO', 'cmd_auto_pulse'),
                       ('BRUP', 'cmd_bright_cycle_pulse')):
            if kw == k:
                out[cmd] = 1
    elif clen == 6 and kw == 'BRGT' and digit(ord('0'), ord('4')):
        out['cmd_bright_set'] = arg - 0x30
        out['cmd_bright_set_v'] = 1
    elif clen == 6 and kw == 'MODE' and digit(ord('0'), ord('9')):
        out['cmd_mode'] = arg - 0x30
        out['cmd_mode_set'] = 1
    elif clen == 6 and kw == 'MARQ' and digit(ord('0'), ord('1')):
        out['cmd_marquee'] = arg - 0x30
        out['cmd_marquee_set'] = 1
    elif clen == 6 and kw == 'IMGX' and digit(ord('1'), ord('4')):
        out['cmd_img_sel'] = arg - 0x30 - 1
        out['cmd_img_sel_set'] = 1
    elif clen == 6 and kw == 'FILT' and digit(ord('0'), ord('9')):
        out['cmd_filt'] = arg - 0x30
        out['cmd_filt_set'] = 1
    elif clen == 6 and kw == 'FONT' and digit(ord('0'), ord('1')):
        out['cmd_font'] = arg - 0x30
        out['cmd_font_set'] = 1
    elif clen == 6 and kw == 'MUSC' and digit(ord('0'), ord('1')):
        out['cmd_audio'] = arg - 0x30
        out['cmd_audio_set'] = 1
    elif clen == 6 and kw == 'SPED' and digit(ord('1'), ord('8')):
        out['cmd_speed'] = arg - 0x30
        out['cmd_speed_set'] = 1
    elif clen == 6 and kw == 'ALRM' and digit(ord('0'), ord('3')):
        out['cmd_emg'] = arg - 0x30
        out['cmd_emg_set'] = 1
    elif clen == 6 and kw == 'VOLM' and digit(ord('0'), ord('2')):
        out['cmd_vol'] = arg - 0x30
        out['cmd_vol_set'] = 1
    return out


class System(object):
    """Mirrors every register the emergency path adds, in all three domains."""

    def __init__(self, emergency_enable=1, release_ms=20,
                 ticks_per_ms=TICKS_PER_MS_FAST, burn_sec=0,
                 manual_type=MANUAL_TYPE, auto_type=AUTO_TYPE,
                 vol_default=VOL_FULL, symmetric=0, burn_stuck=0):
        self.emergency_enable = emergency_enable
        self.release_ms = release_ms
        self.ticks_per_ms = ticks_per_ms
        self.burn_sec = burn_sec
        self.manual_type = manual_type
        self.auto_type = auto_type
        # NEGATIVE CONTROL ONLY: debounce the make the same as the break. Nothing
        # on the happy path constructs a System with this set. It changes how long
        # the SET waits, not how long the window is -- doubling cnt_max instead
        # would leave the make instant and the negative control vacuous.
        self.symmetric = symmetric
        self.burn_stuck = burn_stuck
        self.cnt_max = release_ms * ticks_per_ms

        self.t = 0                    # merged time axis, ns
        self.clk_n = 0
        self.sd_n = 0
        self.vid_n = 0
        self.frame_idx = 0
        self.decide_frame = None      # frame index when emg_state first went live

        # injectable primary inputs
        self.rx = []                  # pending UART bytes, consumed one per clk
        self.ffcnt = 0                # consecutive 0xFF, as the RTL counts it
        self.pend = b''               # accumulated payload bytes
        self.pin_man = 1              # idle high: PULLUP, dry contact pulls to GND
        self.pin_aut = 1
        self.key1 = 0
        self.key2 = 0
        self.tone_left = TONE_LEFT
        self.mus_left = MUS_LEFT

        s = {}
        for k in STATE_KEYS:
            s[k] = 0
        # Registers that exist in the RTL but are deliberately left out of
        # STATE_KEYS: the two release counters and the frame generator. They are
        # phase state, not observable behaviour, so letting them differ is what
        # keeps the snapshot equalities in Passes C and H about the feature and
        # not about when each System happened to be constructed.
        for k in ('mcnt', 'acnt', 'vid_div', 'frame_start'):
            s[k] = 0
        # idle-high pin synchronisers, and the pre-existing reset values top uses
        for k in ('ms0', 'ms1', 'ms2', 'as0', 'as1', 'as2', 'vs', 'vs_d'):
            s[k] = 1
        s['brightness'] = 2
        s['marq_ovr_val'] = 1
        s['speed_lat'] = 1
        s['vol_level'] = vol_default
        s['vol_s0'] = vol_default
        s['vol_v1'] = vol_default
        s['burn_type'] = TYPE_FIRE
        self.st = s

        # clk-domain command wires: pure functions of the parser, recomputed each
        # edge, seeded here only so the keys exist.
        for k in ('cmd_next_pulse', 'cmd_auto_pulse', 'cmd_bright_cycle_pulse',
                  'cmd_bright_set_v', 'cmd_mode_set', 'cmd_marquee_set',
                  'cmd_img_sel_set', 'cmd_filt_set', 'cmd_font_set',
                  'cmd_audio_set', 'cmd_speed_set', 'cmd_emg_set',
                  'cmd_vol_set', 'cmd_bright_set', 'cmd_mode', 'cmd_marquee',
                  'cmd_img_sel', 'cmd_filt', 'cmd_font', 'cmd_audio',
                  'cmd_speed', 'cmd_emg', 'cmd_vol'):
            s[k] = 0

        self.log = {'emg_up_clk': None, 'emg_down_clk': None}

    # -- combinational mirrors of the RTL's assigns ---------------------
    @staticmethod
    def min_live(a, b):
        """Lowest non-zero code wins, which is what makes 1 > 2 > 3 arithmetic."""
        if a == 0:
            return b
        if b == 0:
            return a
        return a if a < b else b

    def resolved(self):
        """The (active, type) the state register loads on this edge."""
        s = self.st
        typ = 0
        if s['alvl']:
            typ = self.min_live(typ, self.auto_type)
        if s['mlvl']:
            typ = self.min_live(typ, self.manual_type)
        if s['req_cmd']:
            typ = self.min_live(typ, s['req_cmd'])
        return (1 if typ else 0), typ

    def hold(self):
        """top's `wire hold = EMERGENCY_ENABLE & emg_state[2]`."""
        return self.emergency_enable & ((self.st['emg_state'] >> 2) & 1)

    def cmd_gate(self):
        return 1 - self.hold()

    def key_gate(self):
        return 1 - (self.emergency_enable & self.st['hold_sd'])

    def siren_sel(self):
        """The ONLY consumer of the fast video_clk crossing: alarm_siren's I_en."""
        return self.emergency_enable & self.st['emg_act_v1']

    def buzzer_on(self):
        """buzzer_beep is in clk, not video_clk: it never crosses, so it is exactly
        the hold level. Top's 2FF pair is for the siren, which has to be muxed into
        a video_clk PCM stream; a horn on a pin has no such reason to wait."""
        return self.hold()

    def audio_src_left(self):
        """4-way priority: siren > (WAV | tone) x gain. See top's assign."""
        if self.siren_sel():
            return SIREN_LEFT
        raw = self.mus_left if self.st['music_en'] else self.tone_left
        vol = self.st['vol_v1'] if self.emergency_enable else VOL_FULL
        if vol == VOL_MUTE:
            return 0
        if vol == VOL_MID:
            return raw >> 2
        return raw

    def audio_valid(self):
        """A constant 1. top's expression does name selects, including the alarm's,
        and that is still safe only because EVERY arm emits an unbroken 48 kHz
        stream -- which is what Pass I checks alarm_siren.v for, and what would
        break if anyone ever gated a valid by its own enable or by a mute."""
        return 1

    def snapshot(self):
        return tuple(self.st[k] for k in STATE_KEYS)

    def emg_snapshot(self):
        """Only what the feature can move -- see PREEXISTING_KEYS/EMG_KEYS."""
        return tuple(self.st[k] for k in EMG_KEYS)

    # -- one merged ns step ---------------------------------------------
    def tick(self):
        t = self.t
        self.t += 1
        s = self.st
        old = dict(s)                # non-blocking: every RHS reads pre-edge state

        do_clk = (t % CLK_PERIOD) == CLK_OFF
        do_sd = (t % SD_PERIOD) == SD_OFF
        do_vid = (t % VID_PERIOD) == VID_OFF

        if do_clk:
            self.clk_n += 1
            strobes = self._consume_byte()
            for k in ('cmd_next_pulse', 'cmd_auto_pulse',
                      'cmd_bright_cycle_pulse', 'cmd_bright_set_v',
                      'cmd_mode_set', 'cmd_marquee_set', 'cmd_img_sel_set',
                      'cmd_filt_set', 'cmd_font_set', 'cmd_audio_set',
                      'cmd_speed_set', 'cmd_emg_set', 'cmd_vol_set'):
                s[k] = 0
            gate = self.cmd_gate()
            # Only the strobes need the freeze: every consumer writes its latch on
            # a strobe, so the value buses simply go unused while held.
            for k in ('cmd_next_pulse', 'cmd_auto_pulse',
                      'cmd_bright_cycle_pulse', 'cmd_bright_set_v',
                      'cmd_mode_set', 'cmd_marquee_set', 'cmd_img_sel_set',
                      'cmd_filt_set', 'cmd_font_set', 'cmd_audio_set',
                      'cmd_speed_set'):
                s[k] = strobes.get(k, 0) * gate
            s['cmd_emg_set'] = strobes.get('cmd_emg_set', 0)
            s['cmd_vol_set'] = strobes.get('cmd_vol_set', 0)
            for v in ('cmd_bright_set', 'cmd_mode', 'cmd_marquee', 'cmd_img_sel',
                      'cmd_filt', 'cmd_font', 'cmd_audio', 'cmd_speed',
                      'cmd_emg', 'cmd_vol'):
                if v in strobes:
                    s[v] = strobes[v]

            self._clk_domain(old)

        if do_sd:
            self.sd_n += 1
            s['hold_s0'] = self.hold()
            s['hold_sd'] = old['hold_s0']
            k1 = self.key1 & self.key_gate()
            s['key1_seen'] = k1
            if k1 and not old['key1_seen']:
                s['next_press_sd'] = old['next_press_sd'] + 1

        if do_vid:
            self.vid_n += 1
            self._vid_domain(old)

    def _consume_byte(self):
        """Feed one UART byte per clk edge through the framed-parser stand-in."""
        if not self.rx:
            return {}
        b, self.rx = self.rx[0], self.rx[1:]
        if b == 0xFF:
            self.ffcnt += 1
            if self.ffcnt == 3 and self.pend:
                out = parse_cmd(self.pend)
                self.pend = b''
                self.ffcnt = 0
                return out
            return {}
        self.ffcnt = 0
        self.pend += bytes([b])
        return {}

    def _debounce(self, old, sync_key, lvl_key, cnt_key):
        """
        One hard-line input: a dry contact that pulls to GND when it fires, so the
        synced 0 is the alarm.

        Asymmetric on purpose. SET follows the 3FF-synced level with no wait, so
        the anti-chatter filter can never delay the thing it exists to filter --
        that is what keeps the <=1 frame headline true on the wire. RELEASE needs
        cnt_max consecutive inactive samples, because a contact that opens and
        slams shut again (a hand on a Dupont line, a chattering relay) must not
        end an alarm. The counter re-arms on every active sample, so a bounce
        restarts the countdown from the far end.

        symmetric=1 is the negative control Pass E runs and nothing else: it holds
        the SET for the same window, which on hardware costs 20 ms against a
        16.8 ms frame.
        """
        s = self.st
        active = (old[sync_key] == 0)
        if not active:
            if old[lvl_key]:
                if old[cnt_key] == 0:
                    s[lvl_key] = 0
                else:
                    s[cnt_key] = old[cnt_key] - 1
            elif self.symmetric:
                s[cnt_key] = 0
        elif not self.symmetric:
            s[lvl_key] = 1
            s[cnt_key] = self.cnt_max
        elif old[cnt_key] >= self.cnt_max:
            s[lvl_key] = 1
        else:
            s[cnt_key] = old[cnt_key] + 1

    def _clk_domain(self, old):
        s = self.st
        # 3FF pin synchronisers
        s['ms0'] = self.pin_man
        s['as0'] = self.pin_aut
        s['ms1'], s['ms2'] = old['ms0'], old['ms1']
        s['as1'], s['as2'] = old['as0'], old['as1']

        # One unit, two instances: the two hard lines differ only in which register
        # names they own, so they share a helper rather than being pasted twice.
        self._debounce(old, 'ms2', 'mlvl', 'mcnt')
        self._debounce(old, 'as2', 'alvl', 'acnt')

        # ---- the req_cmd load, the RTL's second always block ------------------
        # Two sources, one mux, operator first. Not a race in either direction:
        # the sequencer publishes a value plus a one-cycle valid, so a coincident
        # ALRM simply wins the mux and the sequencer keeps its own time.
        if self.emergency_enable and (old['cmd_emg_set'] or old['burn_req_v']):
            s['req_cmd'] = (old['cmd_emg'] if old['cmd_emg_set']
                            else old['burn_req'])

        # ---- burn-in sequencer, the RTL's first always block ------------------
        if self.emergency_enable and self.burn_sec:
            wrap_at = self.burn_sec * 1000 * self.ticks_per_ms
            s['burn_req_v'] = 0
            if old['burn_cnt'] + 1 >= wrap_at:
                s['burn_cnt'] = 0
                s['burn_on'] = 0 if old['burn_on'] else 1
                nxt = 1 + (old['burn_type'] % 3)          # 1 -> 2 -> 3 -> 1
                if old['burn_on'] == 0:
                    s['burn_type'] = nxt
                    s['burn_req'] = nxt
                else:
                    s['burn_req'] = 0
                s['burn_req_v'] = 1
                # NEGATIVE CONTROL ONLY: drop the release publish and keep the
                # counter running, so the takeover can never be let go.
                if self.burn_stuck and old['burn_on']:
                    s['burn_req_v'] = 0
            else:
                s['burn_cnt'] = old['burn_cnt'] + 1

        if self.emergency_enable and old['cmd_vol_set']:
            s['vol_level'] = old['cmd_vol']

        act, typ = self.resolved()
        new_state = ((act & 1) << 2) | (typ & 3)
        if new_state != old['emg_state']:
            s['emg_tgl'] = 1 - old['emg_tgl']
        s['emg_state'] = new_state
        if old['emg_state'] == 0 and new_state != 0:
            self.log['emg_up_clk'] = self.clk_n
            self.decide_frame = self.frame_idx
        elif old['emg_state'] != 0 and new_state == 0:
            self.log['emg_down_clk'] = self.clk_n

        # ---- the pre-existing latches, written exactly as top writes them ----
        if old['cmd_bright_set_v']:
            s['brightness'] = old['cmd_bright_set']
        elif old['cmd_bright_cycle_pulse']:
            s['brightness'] = (old['brightness'] + 1) % 5
        if old['cmd_mode_set']:
            s['mode_ovr_val'] = old['cmd_mode']
            s['mode_ovr_en'] = 1
        if old['cmd_marquee_set']:
            s['marq_ovr_val'] = old['cmd_marquee']
            s['marq_ovr_en'] = 1
        if old['cmd_filt_set']:
            s['filt_val'] = old['cmd_filt']
        if old['cmd_font_set']:
            s['font_val'] = old['cmd_font']
        if old['cmd_audio_set']:
            s['music_en'] = old['cmd_audio']
        if old['cmd_img_sel_set']:
            s['img_sel_lat'] = old['cmd_img_sel']
            s['img_tgl'] = 1 - old['img_tgl']
        if old['cmd_speed_set']:
            s['speed_lat'] = old['cmd_speed']
            s['spd_tgl'] = 1 - old['spd_tgl']
        if old['cmd_next_pulse']:
            s['next_tgl'] = 1 - old['next_tgl']
        if old['cmd_auto_pulse']:
            s['auto_tgl'] = 1 - old['auto_tgl']

    def _vid_domain(self, old):
        s = self.st
        state = self.st['emg_state']
        s['emg_act_s0'] = (state >> 2) & 1
        s['emg_act_v1'] = old['emg_act_s0']
        s['emg_type_s0'] = state & 3
        s['emg_type_v1'] = old['emg_type_s0']
        s['etgl_s0'] = old['emg_tgl']
        s['etgl_s1'] = old['etgl_s0']
        s['etgl_s2'] = old['etgl_s1']
        s['vol_s0'] = old['vol_level']
        s['vol_v1'] = old['vol_s0']

        if old['etgl_s1'] ^ old['etgl_s2']:
            s['estg_act'] = (state >> 2) & 1
            s['estg_type'] = state & 3

        # frame generator: one vsync falling edge every FRAME_VCLKS video clocks
        s['frame_start'] = 0
        s['vs_d'] = old['vs']
        s['vs'] = 0 if old['vid_div'] >= FRAME_VCLKS - 4 else 1
        if old['vs_d'] and not old['vs']:
            s['frame_start'] = 1
            self.frame_idx += 1
        s['vid_div'] = 0 if old['vid_div'] >= FRAME_VCLKS - 1 else old['vid_div'] + 1
        if s['frame_start']:
            s['ef_act'] = old['estg_act']
            s['ef_type'] = old['estg_type']

    # -- drivers ---------------------------------------------------------
    def send_cmd(self, cmd):
        self.rx.extend(frame_bytes(cmd))

    def settle(self, clk_cycles):
        """Advance at least clk_cycles clk edges, however long it really takes."""
        target = self.clk_n + clk_cycles
        guard = (clk_cycles + 20) * CLK_PERIOD * 2
        for _ in range(guard):
            self.tick()
            if self.clk_n >= target:
                break

    def settle_vid(self, vid_cycles):
        target = self.vid_n + vid_cycles
        guard = (vid_cycles + 20) * VID_PERIOD * 2
        for _ in range(guard):
            self.tick()
            if self.vid_n >= target:
                break

    def run_until(self, pred, limit_vid):
        """
        Step until pred(self) is true. `limit_vid` is in VIDEO CLOCKS -- the same
        unit the return value uses -- so the loop has to convert it to the
        nanosecond axis the model runs on. A frame is FRAME_VCLKS video clocks but
        8400 ns, so passing the limit through unconverted expires the search about
        40x too early and every caller reports "never happened".
        """
        start = self.vid_n
        for _ in range(limit_vid * VID_PERIOD + VID_PERIOD):
            self.tick()
            if pred(self):
                return self.vid_n - start
        return None


class Result(object):
    def __init__(self):
        self.rows = []
        self.failed = 0

    def add(self, ok, name, detail):
        self.rows.append((ok, name, detail))
        if not ok:
            self.failed += 1
        print("  [%s] %-54s %s" % ("PASS" if ok else "FAIL", name, detail))


# ---------------------------------------------------------------------------
# Pass A -- takeover latency, swept over the whole frame
# ---------------------------------------------------------------------------
def pass_a(res, verbose):
    print("=" * 78)
    print("A. Takeover latency: decision -> first alarm frame, every phase")
    print("=" * 78)

    bound = FRAME_VCLKS + CDC_VCLKS + 1
    limit = FRAME_VCLKS * 3 + 50
    worst, worst_at, failures, frames_over = 0, None, [], 0
    phases = range(0, FRAME_VCLKS, 5)

    for phase in phases:
        s = System()
        s.settle_vid(phase)
        s.send_cmd("ALRM 1")
        dv = s.run_until(lambda x: x.st['ef_act'] == 1, limit)
        if dv is None:
            failures.append((phase, 'never'))
            continue
        frames = s.frame_idx - (s.decide_frame if s.decide_frame is not None
                                else s.frame_idx)
        if dv > worst:
            worst, worst_at = dv, phase
        if frames > 1:
            frames_over += 1
        if verbose:
            print("      phase %3d -> %3d video clk, %d frame boundaries"
                  % (phase, dv, frames))

    res.add(not failures, "alarm reaches the panel from every frame phase",
            "%d phases swept, %d never took over" % (len(list(phases)),
                                                      len(failures)))
    res.add(worst <= bound,
            "worst-case latency <= one frame + CDC depth",
            "max %d video clk at phase %s, bound %d (FRAME_VCLKS=%d + CDC=%d)"
            % (worst, worst_at, bound, FRAME_VCLKS, CDC_VCLKS))
    res.add(frames_over == 0,
            "never more than one frame boundary is crossed",
            "%d phases needed 2+ frames" % frames_over)

    # The audio/buzzer path skips the frame-atomic stage and must lead.
    a = System()
    a.send_cmd("ALRM 1")
    da = a.run_until(lambda x: x.st['emg_act_v1'] == 1, limit)
    v = System()
    v.send_cmd("ALRM 1")
    dv = v.run_until(lambda x: x.st['ef_act'] == 1, limit)
    res.add(da is not None and dv is not None and da <= dv and dv - da >= 1,
            "audio/buzzer path leads the pixel path",
            "audio %d video clk, pixels %d (pixels wait for no tearing)"
            % (da, dv))

    worst_ms = float(FRAME_VCLKS + CDC_VCLKS) / FRAME_VCLKS * FRAME_MS
    res.add(abs(FRAME_MS - 16.80) < 0.02 and worst_ms < 2.0 * FRAME_MS,
            "headline number is the shipped 640x480p60 geometry",
            "%dx%d @ %.3f MHz = %.2f ms/frame; worst takeover %.2f ms"
            % (H_TOTAL, V_TOTAL, PIXEL_CLK_MHZ, FRAME_MS, worst_ms))


# ---------------------------------------------------------------------------
# Pass B -- single stage, forced, explicit release
# ---------------------------------------------------------------------------
def pass_b(res, verbose):
    print("=" * 78)
    print("B. Single-stage forced takeover, explicit release, no timeout")
    print("=" * 78)

    s = System()
    s.send_cmd("ALRM 1")
    s.settle(30)
    up_state = s.st['emg_state']
    f0 = s.frame_idx
    s.settle_vid(FRAME_VCLKS * 50)
    res.add(s.st['ef_act'] == 1 and s.st['emg_state'] == up_state
            and s.frame_idx - f0 == 50,
            "alarm survives 50 idle frames with nothing touching it",
            "state=%d after %d frames -- no timeout in the design"
            % (s.st['emg_state'], s.frame_idx - f0))

    s.send_cmd("ALRM 0")
    s.settle(30)
    s.settle_vid(FRAME_VCLKS * 2)
    res.add(s.st['emg_state'] == 0 and s.st['ef_act'] == 0,
            "ALRM 0 is the command path's only release",
            "state=%d frame-latched=%d" % (s.st['emg_state'], s.st['ef_act']))

    s = System()
    s.send_cmd("ALRM 3")
    s.settle(30)
    depth1 = s.st['emg_state']
    s.send_cmd("ALRM 2")
    s.settle(30)
    res.add((depth1 >> 2) == 1 and (s.st['emg_state'] >> 2) == 1
            and (s.st['emg_state'] & 3) == TYPE_EVAC,
            "no stacking: a second ALRM n replaces, never nests",
            "active stays 1 throughout, type %d -> %d"
            % (depth1 & 3, s.st['emg_state'] & 3))

    # Release, like assert, must be frame-atomic: exactly one transition.
    s = System()
    s.send_cmd("ALRM 1")
    s.run_until(lambda x: x.st['ef_act'] == 1, FRAME_VCLKS * 3)
    s.send_cmd("ALRM 0")
    s.tick()
    flips, seen = 0, s.st['ef_act']
    for _ in range(FRAME_VCLKS * 3 * VID_PERIOD):   # 3 frames on the ns axis
        s.tick()
        if s.st['frame_start'] and s.st['ef_act'] != seen:
            flips += 1
            seen = s.st['ef_act']
    res.add(flips == 1 and seen == 0,
            "release lands on exactly one frame boundary",
            "%d transitions of the frame-atomic enable over 3 frames" % flips)


# ---------------------------------------------------------------------------
# Pass C -- the merge-point freeze
# ---------------------------------------------------------------------------
def pass_c(res, verbose):
    print("=" * 78)
    print("C. Command freeze at the merge point (and the same commands live)")
    print("=" * 78)

    base = System().snapshot()
    for cmd in FREEZE_CMDS:
        live = System()
        live.send_cmd(cmd)
        live.settle(30)
        live.settle_vid(FRAME_VCLKS * 2)
        changed_live = live.snapshot() != base

        s = System()
        s.send_cmd("ALRM 1")
        s.settle(30)
        s.settle_vid(FRAME_VCLKS)
        before = s.snapshot()
        for _ in range(3):                     # hammer it, in case of phasing
            s.send_cmd(cmd)
            s.settle(30)
        s.settle_vid(FRAME_VCLKS * 2)
        after = s.snapshot()

        res.add(changed_live and before == after,
                "'%s' frozen under alarm, live without it" % cmd,
                "control changes state: %s; 3 hammering sends moved nothing: %s"
                % (changed_live, before == after))

    s = System()
    s.send_cmd("ALRM 1")
    s.settle(30)
    s.send_cmd("ALRM 2")
    s.settle(30)
    s.send_cmd("VOLM 0")
    s.settle(30)
    res.add((s.st['emg_state'] & 3) == TYPE_EVAC
            and s.st['vol_level'] == VOL_MUTE,
            "ALRM and VOLM stay live while everything else freezes",
            "type=%d vol=%d" % (s.st['emg_state'] & 3, s.st['vol_level']))

    # Physical key1: advances the carousel free, swallowed under the alarm.
    s = System()
    s.settle(30)
    s.key1 = 1
    s.settle(3)
    s.key1 = 0
    s.settle(30)
    free = s.st['next_press_sd']

    s.send_cmd("ALRM 1")
    s.settle(30)
    held_at = s.st['hold_sd']
    s.key1 = 1
    s.settle(3)
    s.key1 = 0
    s.settle(60)
    under = s.st['next_press_sd']

    s.send_cmd("ALRM 0")
    s.settle(30)
    s.settle(SD_PERIOD * 20)
    s.key1 = 1
    s.settle(3)
    s.key1 = 0
    s.settle(60)
    resumed = s.st['next_press_sd']

    res.add(free == 1 and held_at == 1 and under == 1 and resumed == 2,
            "key1 works free, is swallowed under alarm, works again after",
            "free=%d hold_sd=%d under=%d after release=%d"
            % (free, held_at, under, resumed))


# ---------------------------------------------------------------------------
# Pass D -- three requestors, fail-safe release AND, type priority
# ---------------------------------------------------------------------------
def pass_d(res, verbose):
    print("=" * 78)
    print("D. Multi-source fusion, fail-safe release, type priority")
    print("=" * 78)

    s = System()
    s.send_cmd("ALRM 3")
    s.settle(30)
    s.pin_aut = 0
    s.settle(30)
    res.add((s.st['emg_state'] & 3) == TYPE_FIRE,
            "T2 closed while a 通用 alarm is up escalates to 火警",
            "type=%d" % (s.st['emg_state'] & 3))
    s.send_cmd("ALRM 0")
    s.settle(60)
    res.add(s.st['emg_state'] != 0,
            "ALRM 0 alone does NOT clear a held T2 contact",
            "state=%d -- release is an AND over the requestors"
            % s.st['emg_state'])
    s.pin_aut = 1
    s.settle(s.cnt_max + 20)
    res.add(s.st['emg_state'] == 0,
            "releasing the last live requestor clears the alarm",
            "state=%d after the release window" % s.st['emg_state'])

    # Columns are written in the order a reader reasons in: which CONTACTS ARE
    # CLOSED. The pins themselves are active low (PULLUP, a dry contact pulls the
    # line to GND), so each flag is inverted on the way in -- mixing those two up
    # is what made an earlier revision of this table expect 疏散 from a board whose
    # fire contact was held shut.
    cases = [
        (TYPE_GEN, 0, 0, TYPE_GEN, "command only"),
        (TYPE_GEN, 0, 1, TYPE_FIRE, "T2 fire beats a 通用 command"),
        (TYPE_GEN, 1, 0, TYPE_EVAC, "T1 evac beats a 通用 command"),
        (TYPE_GEN, 1, 1, TYPE_FIRE, "T1+T2, fire wins"),
        (TYPE_FIRE, 1, 0, TYPE_FIRE, "command fire, T1 held"),
        (TYPE_EVAC, 0, 1, TYPE_FIRE, "a held T2 fire outranks ALRM 2"),
    ]
    for cmd_t, t1, t2, want, why in cases:
        s = System()
        s.pin_man = 0 if t1 else 1
        s.pin_aut = 0 if t2 else 1
        s.send_cmd("ALRM %d" % cmd_t)
        s.settle(40)
        res.add((s.st['emg_state'] & 3) == want,
                "priority: %s -> type %d" % (why, want),
                "got %d (cmd=%d T1 closed=%d T2 closed=%d)"
                % (s.st['emg_state'] & 3, cmd_t, t1, t2))

    s = System()
    s.send_cmd("ALRM 3")
    s.settle(40)
    s.settle_vid(FRAME_VCLKS * 3)
    frame_at_up = s.frame_idx
    s.send_cmd("ALRM 1")
    s.settle(20)
    res.add((s.st['emg_state'] & 3) == TYPE_FIRE and s.st['ef_act'] == 1
            and s.frame_idx - frame_at_up <= 1,
            "escalation 通用->火警 changes content, never re-times",
            "type=%d, still active, %d frames elapsed"
            % (s.st['emg_state'] & 3, s.frame_idx - frame_at_up))

    s = System()
    s.pin_aut = 0
    s.settle(40)
    up = s.st['emg_state']
    s.send_cmd("ALRM 3")
    s.settle(60)
    res.add((up & 3) == TYPE_FIRE and (s.st['emg_state'] & 3) == TYPE_FIRE,
            "ALRM 3 cannot de-escalate a live T2 fire contact",
            "type stays %d" % (s.st['emg_state'] & 3))

    # Both hardlines, one type each: the pin identity fixes the semantics.
    s = System()
    s.pin_man = 0
    s.settle(40)
    t_man = s.st['emg_state'] & 3
    s2 = System()
    s2.pin_aut = 0
    s2.settle(40)
    t_aut = s2.st['emg_state'] & 3
    res.add(t_man == TYPE_EVAC and t_aut == TYPE_FIRE,
            "T1 defaults to 疏散, T2 to 火警",
            "T1->%d T2->%d (both are parameters)" % (t_man, t_aut))


# ---------------------------------------------------------------------------
# Pass E -- asymmetric debounce
# ---------------------------------------------------------------------------
def pass_e(res, verbose):
    print("=" * 78)
    print("E. Asymmetric debounce: immediate make, timed break")
    print("=" * 78)

    s = System()
    made = s.clk_n
    s.pin_man = 0
    armed = s.run_until(lambda x: x.st['mlvl'] == 1, 40)
    res.add(armed is not None and 1 <= armed <= 5,
            "make arms in the 3-FF synchroniser latency only",
            "%d ns after the pin falls (3 sync FFs, no debounce wait)" % armed)

    s = System()
    f0 = s.frame_idx
    s.pin_man = 0
    dv = s.run_until(lambda x: x.st['ef_act'] == 1, FRAME_VCLKS * 3 + 50)
    res.add(dv is not None and dv <= FRAME_VCLKS + CDC_VCLKS + 1
            and s.frame_idx - f0 <= 1,
            "a hardwire make reaches the panel inside one frame",
            "%d video clk, %d frame boundaries" % (dv, s.frame_idx - f0))

    s = System()
    s.pin_man = 0
    s.settle(s.cnt_max + 10)
    res.add(s.st['emg_state'] != 0, "T1 held -> alarm up",
            "level=%d state=%d" % (s.st['mlvl'], s.st['emg_state']))

    # bounce just short of the window must not clear
    s.pin_man = 1
    s.settle(s.cnt_max - 2)
    s.pin_man = 0
    s.settle(20)
    res.add(s.st['emg_state'] != 0,
            "a bounce 2 ticks short of the release window does NOT clear",
            "state=%d, window=%d" % (s.st['emg_state'], s.cnt_max))

    # a clean break must
    s.pin_man = 1
    s.settle(s.cnt_max + 20)
    res.add(s.st['emg_state'] == 0, "a clean break does clear it",
            "state=%d after the full window" % s.st['emg_state'])

    # NEGATIVE CONTROL: debounce the make the same way and the headline dies.
    s = System(symmetric=1)
    s.pin_man = 0
    f0 = s.frame_idx
    dv = s.run_until(lambda x: x.st['ef_act'] == 1, FRAME_VCLKS * 6 + 100)
    crossed = s.frame_idx - f0
    res.add(dv is not None and dv > FRAME_VCLKS + CDC_VCLKS + 1 and crossed >= 2,
            "NEGATIVE CONTROL: symmetric debounce breaks the <=1 frame claim",
            "%d video clk to take over, %d frame boundaries; hardware is 20 ms "
            "of make against a %.2f ms frame" % (dv, crossed, FRAME_MS))


# ---------------------------------------------------------------------------
# Pass F -- the shipped 20 ms release window at the shipped 50 MHz
# ---------------------------------------------------------------------------
def pass_f(res, verbose):
    print("=" * 78)
    print("F. Real timing: RELEASE_MS=20 at CLK_FREQ_HZ=50 MHz")
    print("=" * 78)

    s = System(ticks_per_ms=TICKS_PER_MS_REAL)
    s.pin_aut = 0
    s.settle(10)
    res.add(s.st['alvl'] == 1, "T2 arms immediately at real timing",
            "level armed after %d clk edges" % s.clk_n)
    s.pin_aut = 1
    base = s.clk_n                      # measure the window from here, not from t=0
    up_to = s.cnt_max + 40
    cleared_at = None
    for _ in range((up_to + 10) * CLK_PERIOD):
        s.tick()
        if s.st['alvl'] == 0:
            cleared_at = s.clk_n
            break
    # 2 synchroniser FFs still read the closed level (and re-arm the counter),
    # cnt_max inactive samples are the window itself, 1 edge commits the clear.
    want = 2 + s.cnt_max + 1
    span = (cleared_at - base) if cleared_at is not None else None
    ms = (span or 0) * CLK_PERIOD / 1e6
    res.add(span is not None and abs(span - want) <= 2,
            "release window is 20.00 ms, not 2 ms and not 200 ms",
            "%d clk edges = %.3f ms (want %d = %d x %d ms + 3 sync)"
            % (span, ms, want, s.cnt_max // TICKS_PER_MS_REAL, 1))
    res.add(19.9 < ms < 20.2,
            "release debounce matches the 20 ms the keys already use",
            "key_press_debounce is DEBOUNCE_MS=20; this measures %.3f ms" % ms)


# ---------------------------------------------------------------------------
# Pass G -- volume, siren bypass, ACR continuity
# ---------------------------------------------------------------------------
def pass_g(res, verbose):
    print("=" * 78)
    print("G. Volume steps, siren bypass, ACR continuity")
    print("=" * 78)

    for level, want in ((VOL_FULL, TONE_LEFT), (VOL_MID, TONE_LEFT >> 2),
                        (VOL_MUTE, 0)):
        s = System()
        s.send_cmd("VOLM %d" % level)
        s.settle(30)
        s.settle_vid(LEVEL_VCLKS + 2)
        res.add(s.st['vol_v1'] == level and s.audio_src_left() == want,
                "VOLM %d -> tone scaled to 0x%X" % (level, want),
                "vol_v1=%d out=0x%X" % (s.st['vol_v1'], s.audio_src_left()))

    # the same gain must sit on the WAV arm too, not just on the tone
    s = System()
    s.send_cmd("MUSC 1")
    s.settle(30)
    s.send_cmd("VOLM 1")
    s.settle(30)
    s.settle_vid(LEVEL_VCLKS + 2)
    res.add(s.st['music_en'] == 1 and s.audio_src_left() == (MUS_LEFT >> 2),
            "VOLM 1 scales the TF-card WAV identically (one shared stage)",
            "out=0x%X" % s.audio_src_left())

    # the bypass
    s = System()
    s.send_cmd("VOLM 0")
    s.settle(30)
    s.settle_vid(LEVEL_VCLKS + 2)
    muted = s.audio_src_left()
    s.send_cmd("ALRM 1")
    s.settle(30)
    s.settle_vid(LEVEL_VCLKS + 2)
    res.add(muted == 0 and s.audio_src_left() == SIREN_LEFT,
            "VOLM 0 silences the signage but never the siren",
            "muted=0x%X, under alarm=0x%X" % (muted, s.audio_src_left()))

    # audio_valid must be independent of every select that can go silent.
    # NOT "must name no select": the shipped build already muxes mus_valid and
    # tone_valid on music_en_v1 and that is safe, because both arms emit an
    # unbroken 48 kHz valid stream. The things that would actually starve
    # audio_arc_calculate's 48-valids-per-CTS count are the new gain stage and any
    # sample-data signal, so those are what this forbids. The alarm arm's own
    # continuity is Pass I's job, since only the siren module can answer it.
    valid_line = RTL['audio_valid']
    poisoned = [tok for tok in ('vol', 'gain', 'mute', 'left_data', 'right_data')
                if tok in valid_line.replace(' ', '')]
    res.add(bool(valid_line) and not poisoned,
            "assign audio_valid names nothing that can go silent",
            "line: %s" % (valid_line.strip() or "<not found>"))
    res.add(s.audio_valid() == 1 and System().audio_valid() == 1,
            "modelled valid is a constant, so ACR never loses its 48 valid/frame",
            "valid is 1 with and without the alarm up")

    # three latencies, in the order the architecture claims them: the horn never
    # leaves clk, the siren crosses once, the panel waits for a frame boundary.
    b = System()
    b.send_cmd("ALRM 1")
    da = b.run_until(lambda x: x.buzzer_on() == 1, FRAME_VCLKS * 3 + 50)
    b2 = System()
    b2.send_cmd("ALRM 1")
    ds = b2.run_until(lambda x: x.siren_sel() == 1, FRAME_VCLKS * 3 + 50)
    b3 = System()
    b3.send_cmd("ALRM 1")
    dv = b3.run_until(lambda x: x.st['ef_act'] == 1, FRAME_VCLKS * 3 + 50)
    res.add(None not in (da, ds, dv) and da < ds < dv,
            "buzzer (no crossing) beats siren (fast 2FF) beats panel (frame start)",
            "buzzer at %d video clk, siren at %d, panel at %d" % (da, ds, dv))

    # ---- structural. The ordering above is only as real as the wiring that
    # produces it, and a model cannot see the RTL. Checked against shipped text.
    smap = _instance_src(TOP_SRC, 'u_alarm_siren')
    bmap = _instance_src(TOP_SRC, 'u_buzzer_beep')

    def _connects(port, net, mapping):
        return bool(re.search(r"\.%s\s*\(\s*%s\s*\)" % (port, re.escape(net)),
                              mapping))

    res.add(_connects('I_en', 'emg_act_v1', smap)
            and _connects('I_type', 'emg_type_v1', smap),
            "siren takes its gate and its cadence from the fast pair",
            "port map is %d chars; I_en/I_type must name emg_act_v1/emg_type_v1"
            % len(smap))
    res.add(bool(smap) and 'emg_state_frame' not in smap,
            "nothing frame-latched reaches the audio path",
            "an I_type wired to emg_state_frame would sound the wrong siren for up "
            "to one frame and the model above could not tell")
    res.add(_connects('I_alarm', 'emg_state[2]', bmap)
            and _connects('I_level', 'vol_level', bmap)
            and _connects('O_beep', 'spk', bmap),
            "buzzer is driven from the gated clk-domain state, straight to the pin",
            "I_alarm/I_level/O_beep -> emg_state[2]/vol_level/spk")
    res.add(bool(bmap) and 'video_clk' not in bmap,
            "buzzer never crosses into video_clk",
            "crossing it would put two synchroniser stages in front of the fastest "
            "indication the board has")

    gain = re.search(r"function \[23:0\] vol_gain;(.*?)endfunction", TOP_SRC, re.S)
    body = gain.group(1) if gain else ""
    res.add(bool(body) and '>>>' in body and '$signed' in body
            and re.search(r"[^>]>>[^>]", body) is None,
            "the -12 dB step is an ARITHMETIC shift on a signed operand",
            "every sample constant in this file is positive, so a logical >> would "
            "pass the model and turn -1 into 0x7FFFFF on real PCM; body=%d chars"
            % len(body))
    res.add(not re.search(r"vol_gain\([^)]*siren", TOP_SRC, re.S),
            "the siren arm is outside the gain, so VOLM 0 cannot mute an alarm",
            "the model asserts this behaviourally above; this pins the wiring that "
            "makes it structural rather than a case arm someone can reorder")


# ---------------------------------------------------------------------------
# Shipped RTL text, for the structural checks in G/H/I.
# ---------------------------------------------------------------------------
def _read(*rel):
    here = os.path.dirname(os.path.abspath(__file__))
    path = os.path.abspath(os.path.join(here, *rel))
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            return f.read()
    except IOError:
        return ""


def _find_assign(text, lhs):
    for line in text.splitlines():
        if ("assign %s" % lhs) in line.replace("  ", " "):
            return line
    for line in text.splitlines():
        if line.strip().startswith(lhs) and "=" in line and "assign" not in line:
            return line
    return ""


def _strip_comments(text):
    """Blank out // and /* */ comments, preserving offsets and newlines.

    Offsets are the point: the callers still report line-based findings, and a
    stripper that shortened the text would desynchronise them from the file.
    """
    out = []
    i, n = 0, len(text)
    in_str = False
    while i < n:
        c = text[i]
        two = text[i:i + 2]
        if in_str:
            out.append(c)
            if c == '"':
                in_str = False
            i += 1
        elif c == '"':
            in_str = True
            out.append(c)
            i += 1
        elif two == "//":
            while i < n and text[i] != "\n":
                out.append(" ")
                i += 1
        elif two == "/*":
            while i < n and text[i:i + 2] != "*/":
                out.append("\n" if text[i] == "\n" else " ")
                i += 1
            out.append("  ")
            i += 2
        else:
            out.append(c)
            i += 1
    return "".join(out)


def _instance_src(text, inst):
    """One instance's port map, from its `( ` to the closing `);`. Empty string if
    the instance is not there at all, so callers can write `bool(smap) and ...`.

    Searched in comment-free text on purpose: the top's own prose names instances
    -- `u_alarm_siren (the whole scope disappears, not just the instance)` sits a
    hundred lines above the real one -- and a plain find returns a slice of that
    sentence instead of a port map, which reads as missing wires and a stray
    frame-latched net in a design whose wiring is fine.
    """
    code = _strip_comments(text)
    i = code.find(inst + " (")
    if i < 0:
        return ""
    j = code.find(");", i)
    return code[i:j] if j > 0 else ""


def _param_src(text, mod, inst):
    """One instance's PARAMETER list, i.e. the `mod #(...)` before `) inst (`.

    The companion of _instance_src, and needed because the two halves do not
    overlap: an instance's port map starts at the paren after its name, which is
    on the far side of the parameter block's closing paren. Every override that
    matters at build time -- BURN_SEC, EMERGENCY_ENABLE, TONE_HZ -- lives here, so
    a check that reads only the port map silently cannot see it.
    """
    code = _strip_comments(text)
    i = code.find(inst + " (")
    if i < 0:
        return ""
    j = code.rfind(mod + " #(", 0, i)
    return code[j:i] if j >= 0 else ""


TOP_SRC = _read(os.pardir, "src", "user_source", "hdl_source",
                "top_tf_hdmi_audio.v")
SIREN_SRC = _read(os.pardir, "src", "user_source", "hdl_source",
                  "alarm_siren.v")
BUZZ_SRC = _read(os.pardir, "src", "user_source", "hdl_source",
                 "buzzer_beep.v")
CTRL_SRC = _read(os.pardir, "src", "user_source", "hdl_source",
                 "emergency_ctrl.v")
RTL = {'audio_valid': _find_assign(TOP_SRC, 'audio_valid')}


# ---------------------------------------------------------------------------
# Pass H -- the one-line retreat
# ---------------------------------------------------------------------------
def pass_h(res, verbose):
    print("=" * 78)
    print("H. EMERGENCY_ENABLE=0 retreat: indistinguishable from no feature")
    print("=" * 78)

    barr = ["ALRM 1", "ALRM 3", "VOLM 0", "VOLM 1", "MODE 5", "IMGX 3", "NEXT",
            "BRGT 4", "SPED 6", "FILT 2", "FONT 1", "MUSC 1", "MARQ 0", "AUTO",
            "BRUP", "ALRM 0"]

    off = System(emergency_enable=0)
    for cmd in barr:
        off.send_cmd(cmd)
        off.settle(20)
    off.settle_vid(FRAME_VCLKS * 3)
    quiet = System(emergency_enable=0)
    res.add(off.emg_snapshot() == quiet.emg_snapshot(),
            "EMERGENCY_ENABLE=0: an ALRM/VOLM barrage leaves nothing behind",
            "all %d feature registers identical to a board that heard nothing"
            % len(EMG_KEYS))
    res.add(off.st['ef_act'] == 0 and off.st['emg_act_v1'] == 0
            and off.st['hold_sd'] == 0,
            "alarm layer, audio takeover and key gate all stay dark",
            "frame-atomic=%d fast=%d sd-hold=%d"
            % (off.st['ef_act'], off.st['emg_act_v1'], off.st['hold_sd']))
    # The barrage leaves MUSC 1 selected, so the pre-feature mux is not simply
    # the tone -- evaluate it on the state the barrage actually left behind.
    pre_feature = MUS_LEFT if off.st['music_en'] else TONE_LEFT
    res.add(off.audio_src_left() == pre_feature and off.audio_valid() == 1
            and off.st['vol_v1'] == VOL_FULL,
            "audio path collapses to the pre-feature 2:1 mux at full gain",
            "out=0x%X == music_en ? WAV : tone, vol_v1=%d"
            % (off.audio_src_left(), off.st['vol_v1']))

    off.key1 = 1
    off.settle(3)
    off.key1 = 0
    off.settle(SD_PERIOD * 20)
    res.add(off.buzzer_on() == 0 and off.key_gate() == 1
            and off.st['next_press_sd'] == 1,
            "buzzer never drives and key1 still turns the carousel",
            "buzzer=%d key_gate=%d next_press=%d"
            % (off.buzzer_on(), off.key_gate(), off.st['next_press_sd']))

    on = System(emergency_enable=1)
    on.send_cmd("ALRM 1")
    on.settle(30)
    on.run_until(lambda x: x.st['ef_act'] == 1, FRAME_VCLKS * 3)
    res.add(on.st['ef_act'] == 1 and on.audio_src_left() == SIREN_LEFT,
            "retreat is one-sided: the feature works when enabled",
            "layer=%d audio=0x%X" % (on.st['ef_act'], on.audio_src_left()))

    # Structural. A retreat parameter that gates only a strobe leaves the
    # instance a load and synthesis keeps it -- this project already got caught
    # once, on led[3]. So every output of emergency_ctrl must appear in top only
    # behind EMERGENCY_ENABLE. Checked against the shipped text, not assumed.
    for sig in ('emg_state', 'emg_tgl', 'vol_level'):
        lines = [l for l in TOP_SRC.splitlines()
                 if sig in l and not l.strip().startswith('//')]
        gated = [l for l in lines if 'EMERGENCY_ENABLE' in l
                 or 'emg_gate' in l or 'emg_hold' in l or 'siren_sel' in l
                 or 'emg_layer' in l]
        res.add(bool(lines) and len(gated) >= 1,
                "top reads %s only through a gated wire" % sig,
                "%d use sites, %d of them gated" % (len(lines), len(gated)))

    # ...and gating the inputs is NOT enough for a purely combinational layer.
    # Measured 2026-09-13: with EMERGENCY_ENABLE=0 the three sequential instances
    # left the area report, u_alarm_overlay did not -- it kept 202 lut and 12 seq,
    # because its raster tracker and frame counter free-run off I_de and no
    # constant on I_en removes them. The loop above is satisfied by that build.
    res.add(_layer_is_generated(TOP_SRC),
            "the alarm layer is deleted by a parameter generate, not by folding",
            "measured: gating I_en alone still cost 202 lut / 12 seq at the retreat "
            "value, so 'one line of retreat' would have been a lie for this module")
    unwrapped = TOP_SRC.replace(
        "if (EMERGENCY_ENABLE) begin : g_alarm_overlay",
        "begin : g_alarm_overlay", 1)
    caught = unwrapped != TOP_SRC and not _layer_is_generated(unwrapped)
    res.add(caught,
            "NEGATIVE CONTROL: an unguarded generate is caught",
            "mutation applied=%d, rule rejected it=%d"
            % (1 if unwrapped != TOP_SRC else 0,
               0 if _layer_is_generated(unwrapped) else 1)
            if unwrapped != TOP_SRC else
            "mutation did not apply, so this proved nothing")


# ---------------------------------------------------------------------------
def _valid_is_constant(src):
    """True when every assignment to O_audio_valid in `src` drives a constant.

    What starves audio_arc_calculate's 48-valids-per-CTS count is a valid written
    from anything that can go away -- its own enable, a mute, a FIFO-not-empty
    flag. Constants are safe: the reset and the per-cycle default clear are two of
    them in audio_pcm_player.v's house pattern, and the tick assertion is the 1'b1.
    """
    lines = [l for l in src.splitlines()
             if 'O_audio_valid' in l and '<=' in l
             and not l.strip().startswith('//')]
    consts = [l for l in lines if re.search(r"<=\s*1'b[01]\s*;", l)]
    return bool(lines) and len(consts) == len(lines) and \
           any(re.search(r"<=\s*1'b1\s*;", l) for l in lines)


def _layer_is_generated(src):
    """True when the alarm overlay instance sits inside a generate guarded by
    EMERGENCY_ENABLE, and the disabled branch hands the pixels straight through."""
    m = re.search(r"if\s*\(EMERGENCY_ENABLE\)\s*begin[^:]*:\s*\w+(.*?)endgenerate",
                  src, re.S)
    return bool(m) and 'u_alarm_overlay' in m.group(1) \
        and 'assign vout_data_alarm = vout_data;' in m.group(1)


def _mem_decls(src):
    """Lines that would infer a block RAM: a 2-D memory declaration, or a literal
    BRAM attribute. NOT the substring 'ram' -- that matches 'parameter' and
    'localparam', which every module in this project has, and a check that can
    never pass is not a strict check."""
    decl = re.compile(r'\b(?:reg|wire)\b[^;=\n]*\[[^\]]*\]'
                      r'\s*[A-Za-z_]\w*\s*\[[^\]]*\]')
    return [l for l in src.splitlines()
            if not l.strip().startswith('//')
            and (re.search(r'\bBRAM\b', l) or decl.search(l))]


# Pass I -- siren synthesiser arithmetic
# ---------------------------------------------------------------------------
def pass_i(res, verbose):
    print("=" * 78)
    print("I. Siren synthesiser arithmetic (no BRAM, no DSP)")
    print("=" * 78)

    SR, FULL = 48_000, 1 << 32
    for f_target in (700, 800, 1000, 1200, 1400):
        step = int(round(f_target * FULL / float(SR)))
        f_real = step * SR / float(FULL)
        res.add(abs(f_real - f_target) < 1.0 and 0 < step < FULL,
                "%d Hz from a 32-bit phase accumulator" % f_target,
                "step=%d -> %.4f Hz" % (step, f_real))

    res.add(bool(SIREN_SRC), "alarm_siren.v exists to check",
            "%d bytes" % len(SIREN_SRC))
    if SIREN_SRC:
        # Pass G's other half: the alarm arm of the audio mux is only safe to put
        # on the wire if IT also streams valid unconditionally, which is the rule
        # audio_pcm_player.v states outright -- "valid every tick, even silent".
        vlines = [l.strip() for l in SIREN_SRC.splitlines()
                  if 'O_audio_valid' in l and '<=' in l
                  and not l.strip().startswith('//')]
        ones = [l for l in vlines if re.search(r"<=\s*1'b1\s*;", l)]
        res.add(_valid_is_constant(SIREN_SRC),
                "siren streams audio_valid every tick, even silent",
                "%d assignments, all constants, %d of them the 1'b1 tick assert"
                % (len(vlines), len(ones)))
        # NEGATIVE CONTROL: gate the valid by the module's own enable, the way a
        # reviewer trying to "save power" would, and the rule above must notice.
        gated = re.sub(r"(O_audio_valid\s*<=\s*)1'b1\s*;", r"\g<1>I_en;",
                       SIREN_SRC, count=1)
        n_ctrl = 1 if gated != SIREN_SRC else 0
        res.add(n_ctrl and not _valid_is_constant(gated),
                "NEGATIVE CONTROL: an enable-gated valid is caught",
                "mutation applied=%d, rule rejected it=%d"
                % (n_ctrl, 0 if _valid_is_constant(gated) else 1)
                if n_ctrl else "mutation did not apply, so this proved nothing")

        acc = [l for l in SIREN_SRC.splitlines() if 'phase_acc' in l
               and not l.strip().startswith('//')]
        reloads = [l for l in acc
                   if ('<= 32\'d0' in l or '<= ' in l) and '+' not in l]
        res.add(bool(acc) and not reloads,
                "phase accumulator is advanced, never reloaded",
                "%d lines touch phase_acc, %d of them reload it"
                % (len(acc), len(reloads)))
        body = [l for l in SIREN_SRC.splitlines()
                if not l.strip().startswith('//')]
        mult = [l for l in body if '*' in l and '/*' not in l]
        res.add(not mult, "no multiplier in the siren datapath",
                "%d lines contain '*': %s"
                % (len(mult), mult[0].strip()[:52] if mult else "-"))
        found = _mem_decls(SIREN_SRC)
        res.add(not found, "no waveform ROM, so nothing to infer a memory from",
                "%d memory-shaped declarations; a table would also cost the "
                "BRAM budget this build is short of" % len(found))
        # NEGATIVE CONTROL: a real ROM declaration must be caught. Nothing in this
        # project declares a 2-D memory anywhere (every on-chip storage is a BRAM IP
        # instance or a packed vector), so a synthetic mutation is the only way to
        # give this rule a positive edge at all.
        with_rom = SIREN_SRC.replace(
            "reg  [31:0] S_tick_acc;",
            "reg  [23:0] S_wave_rom [0:255];\nreg  [31:0] S_tick_acc;", 1)
        res.add(with_rom != SIREN_SRC and bool(_mem_decls(with_rom)),
                "NEGATIVE CONTROL: a 256-entry waveform ROM is caught",
                "mutation applied=%d, caught=%d"
                % (1 if with_rom != SIREN_SRC else 0,
                   1 if _mem_decls(with_rom) else 0)
                if with_rom != SIREN_SRC else
                "mutation did not apply, so this proved nothing")


# ---------------------------------------------------------------------------
# Sound shape: parsed out of the shipped text, so these passes cannot drift
# into checking a design nobody built.
# ---------------------------------------------------------------------------
def _v_num(tok):
    """32'd62634940 / 25_000_000 / 10'd500 -> int. None if it is not a number."""
    tok = (tok or "").strip().replace("_", "")
    m = re.match(r"^\d*'[dDhHoObB]([0-9A-Fa-f]+)$", tok)
    if m:
        base = {'d': 10, 'h': 16, 'o': 8, 'b': 2}[tok[tok.index("'") + 1].lower()]
        return int(m.group(1), base)
    return int(tok) if re.match(r"^\d+$", tok) else None


def _tick_guard_span(code):
    """(start, end) offsets of the `if (W_tick) begin ... end` body, or None."""
    g = re.search(r"if\s*\(W_tick\)\s*begin\b", code)
    if not g:
        return None
    depth, end = 1, len(code)
    for tok in re.finditer(r"\bbegin\b|\bend\b", code[g.end():]):
        depth += 1 if tok.group(0) == "begin" else -1
        if depth == 0:
            end = g.end() + tok.start()
            break
    return (g.end(), end)


def _siren_cfg(src):
    """alarm_siren.v's cadence datapath as numbers a scope would measure.

    cfg['error'] lists every shape that could not be found, so a rename fails the
    pass loudly instead of quietly simulating something else. 'per_sample' is the
    one fact no amount of arithmetic can tell you -- where the increment sits
    relative to the 48 kHz tick guard -- so it is read off the block structure.
    """
    code = _strip_comments(src)
    cfg, err = {}, []

    def grab(name, pattern, group=1, flags=0):
        m = re.search(pattern, code, flags)
        if not m:
            err.append("no %s (%s)" % (name, pattern[:34]))
            return None
        return m.group(group)

    cfg['CLK_FREQ_HZ'] = _v_num(grab('CLK_FREQ_HZ',
                                     r"parameter integer CLK_FREQ_HZ\s*=\s*([\d_]+)"))
    cfg['SAMPLE_RATE_HZ'] = _v_num(grab('SAMPLE_RATE_HZ',
                                        r"parameter integer SAMPLE_RATE_HZ\s*=\s*([\d_]+)"))
    cfg['steps'] = dict((n, _v_num(v)) for n, v in re.findall(
        r"localparam \[31:0\] (STEP_\w+)\s*=\s*(32'd[\d_]+)", code))
    alt = grab('W_alt', r"wire\s+W_alt\s*=\s*S_mod_cnt\[\s*(\d+)\s*\]")
    puls = grab('W_pulse', r"wire\s+W_pulse\s*=\s*S_mod_cnt\[\s*(\d+)\s*\]")
    cfg['alt_bit'] = int(alt) if alt else None
    cfg['pulse_bit'] = int(puls) if puls else None
    fire = re.search(r"TYPE_FIRE\)\s*\?\s*\(\s*W_alt\s*\?\s*(STEP_\w+)\s*:\s*"
                     r"(STEP_\w+)\s*\)", code)
    evac = re.search(r"TYPE_EVAC\)\s*\?\s*(STEP_\w+)", code)
    gen = re.search(r":\s*(STEP_\w+)\s*;", code)
    cfg['fire'] = fire.groups() if fire else None
    cfg['evac'] = evac.group(1) if evac else None
    cfg['general'] = gen.group(1) if gen else None
    if not (fire and evac and gen):
        err.append("W_step's three type arms did not all match")
    cfg['evac_gate'] = bool(re.search(
        r"W_audible\s*=\s*I_en\s*&&\s*\(\(I_type\s*==\s*TYPE_EVAC\)\s*\?\s*"
        r"~W_pulse\s*:\s*1'b1\)", code))
    if not cfg['evac_gate']:
        err.append("W_audible is no longer the EVAC-only gate")
    cfg['held_at_zero'] = bool(re.search(r"else\s+S_mod_cnt\s*<=\s*16'd0\s*;", code))
    adv = re.search(r"S_mod_cnt\s*<=\s*S_mod_cnt\s*\+", code)
    cfg['advance_stmt'] = bool(adv)
    span = _tick_guard_span(code)
    cfg['per_sample'] = bool(adv and span and span[0] <= adv.start() < span[1])
    cfg['error'] = err
    return cfg


def _hz(cfg, step_name):
    """Tone a 32-bit phase step really produces at the parsed sample rate."""
    step = cfg['steps'].get(step_name)
    if step is None or not cfg.get('SAMPLE_RATE_HZ'):
        return None
    return step * cfg['SAMPLE_RATE_HZ'] / float(1 << 32)


def _siren_shape(cfg, atype):
    """(list of (Hz, ms each), audible duty) for one type code, or None."""
    if cfg.get('error'):
        return None
    rate = cfg['SAMPLE_RATE_HZ'] if cfg['per_sample'] else cfg['CLK_FREQ_HZ']
    if not rate:
        return None
    half = lambda bit: (1 << bit) * 1000.0 / rate      # noqa: E731 (one-liner)
    if atype == TYPE_FIRE:
        lo, hi = cfg['fire']
        return [(_hz(cfg, lo), half(cfg['alt_bit'])),
                (_hz(cfg, hi), half(cfg['alt_bit']))], 1.0
    if atype == TYPE_EVAC:
        return [(_hz(cfg, cfg['evac']), half(cfg['pulse_bit']))], 0.5
    return [(_hz(cfg, cfg['general']), None)], 1.0


def _buzzer_cfg(src, inst_src):
    """buzzer_beep.v's constants, with top's instance overrides applied."""
    code = _strip_comments(src)
    cfg, err = {}, []

    def grab(name, pattern):
        m = re.search(pattern, code)
        if not m:
            err.append("no %s" % name)
            return None
        return m.group(1)

    def num(name, pattern):
        return _v_num(grab(name, pattern))

    for nm, pat in (('CLK_FREQ_HZ', r"parameter integer CLK_FREQ_HZ\s*=\s*([\d_]+)"),
                    ('TONE_HZ', r"parameter integer TONE_HZ\s*=\s*([\d_]+)"),
                    ('WINDOW_MS', r"parameter integer WINDOW_MS\s*=\s*([\d_]+)")):
        own = num(nm, pat)
        over = re.search(r"\.%s\s*\(\s*([\d_]+)\s*\)" % nm, inst_src)
        cfg[nm] = _v_num(over.group(1)) if over else own
        cfg[nm + '_overridden'] = bool(over)
    for nm, pat in (('ON_FIRE', r"ON_FIRE\s*=\s*([\w]+)\s*;"),
                    ('ON_EVAC', r"ON_EVAC\s*=\s*([\d_]+)\s*;"),
                    ('ON_GEN', r"ON_GEN\s*=\s*([\d_]+)\s*;")):
        raw = grab(nm, pat)
        cfg[nm] = cfg['WINDOW_MS'] if raw == 'WINDOW_MS' else _v_num(raw)
    cfg['HALF_TONE'] = (cfg['CLK_FREQ_HZ'] // cfg['TONE_HZ'] // 2
                        if cfg.get('CLK_FREQ_HZ') and cfg.get('TONE_HZ') else None)
    cfg['MS_TICKS'] = (cfg['CLK_FREQ_HZ'] // 1000) if cfg.get('CLK_FREQ_HZ') else None
    cfg['ladder_guard'] = grab('ladder guard',
                               r"if \((I_alarm && \(I_level != 2'd0\))\) begin")
    cfg['envelope_terms'] = bool(re.search(
        r"W_envelope\s*=\s*I_alarm && \(I_level != 2'd0\) && \(S_win_ms < W_on_ms\)",
        code))
    cfg['silence_driven'] = bool(re.search(r"S_tone_cnt <= 15'd0;\s*O_beep\s*<= 1'b0;",
                                           code, re.S))
    cfg['gated_by_enable'] = bool(re.search(r"end else if \(EMERGENCY_ENABLE\) begin",
                                            code))
    cfg['error'] = err
    return cfg


def _buzzer_walk(clk_hz, tone_hz, window_ms, on_ms, level=2, alarm=1,
                 ladder='armed', n_windows=3):
    """Cycle-accurate walk of buzzer_beep.v's three counters at shrunk constants.

    The tone divider, the ms prescaler and the window ladder are independent
    counters, so dividing all three rates by the same integer leaves the same
    arithmetic and turns a 30 M-edge soak of one 600 ms window into a few hundred.
    ladder='envelope' is the NEGATIVE CONTROL: the shape this file used to have,
    where running the ladder off the envelope instead of the arming level made the
    off-time unreachable.
    """
    half_tone = clk_hz // tone_hz // 2
    ms_ticks = clk_hz // 1000
    tone_cnt = ms_cnt = win = 0
    beep = 0
    envs, beeps = [], []
    for _ in range(int(window_ms * n_windows * ms_ticks)):
        armed = bool(alarm and level != 0)
        sounding = bool(armed and win < on_ms)
        if ladder == 'armed':
            run = armed
        else:
            run = sounding
            if not sounding:
                ms_cnt = win = 0
        if run:
            if ms_cnt >= ms_ticks - 1:
                ms_cnt = 0
                win = 0 if win >= window_ms - 1 else win + 1
            else:
                ms_cnt += 1
        if sounding:
            if tone_cnt >= half_tone - 1:
                tone_cnt = 0
                beep ^= 1
            else:
                tone_cnt += 1
        else:
            tone_cnt = 0
            beep = 0
        envs.append(1 if sounding else 0)
        beeps.append(beep)
    return envs, beeps


def _duty_and_gap(run, ms_ticks):
    """Sounding fraction and longest silence, in ms, over the trailing windows."""
    envs = run[0]
    tail = envs[len(envs) // 3:]
    duty = sum(tail) / float(len(tail))
    longest, cur = 0, 0
    for e in tail:
        cur = 0 if e else cur + 1
        longest = max(longest, cur)
    return duty, longest / float(ms_ticks)


def _measured_tone_hz(envs, beeps, clk_hz):
    """Frequency measured from the O_beep edges themselves, not from the divider.

    Mean edge interval, not edge count over a window: the trailing slice is not a
    whole number of periods, and counting edges across it was 4% high on a 100 Hz
    tone. The first interval is dropped because the slice can start mid-period.
    """
    lo = len(envs) // 3
    edges = [i for i in range(lo + 1, len(envs))
             if envs[i] and envs[i - 1] and beeps[i] != beeps[i - 1]]
    gaps = [b - a for a, b in zip(edges, edges[1:])][1:]
    if not gaps:
        return None
    return clk_hz / float(2 * (sum(gaps) / float(len(gaps))))


# ---------------------------------------------------------------------------
# Pass J -- what the two sound channels actually do differently per type
# ---------------------------------------------------------------------------
def pass_j(res, verbose):
    print("=" * 78)
    print("J. Per-type cadence: the HDMI siren and the on-board horn")
    print("=" * 78)

    cfg = _siren_cfg(SIREN_SRC)
    res.add(not cfg['error'], "alarm_siren.v's cadence datapath parses",
            cfg['error'] and "; ".join(cfg['error']) or
            "steps=%s alt bit%d pulse bit%d @ %d Hz from %d Hz"
            % (sorted(cfg['steps']), cfg['alt_bit'], cfg['pulse_bit'],
               cfg['SAMPLE_RATE_HZ'], cfg['CLK_FREQ_HZ']))

    res.add(bool(cfg.get('advance_stmt')) and bool(cfg.get('per_sample')),
            "the cadence counter advances once per SAMPLE, not per video clock",
            "increment inside the 48 kHz tick guard=%d; at 25 MHz mod_cnt[14] "
            "would toggle every 0.655 ms instead of every 341.3 ms"
            % (1 if cfg.get('per_sample') else 0))

    want_ms = ((1 << 14) * 1000.0 / 48_000.0, (1 << 13) * 1000.0 / 48_000.0)
    if not cfg['error']:
        fire = _siren_shape(cfg, TYPE_FIRE)
        evac = _siren_shape(cfg, TYPE_EVAC)
        gen = _siren_shape(cfg, TYPE_GENERAL)
        f_ms = fire[0][0][1]
        res.add(abs(f_ms - want_ms[0]) < 1.0 and
                all(abs(f - _hz(cfg, s)) < 1.0 for (f, _), s in zip(fire[0], cfg['fire'])),
                "fire = 800/1000 Hz two-tone, %.1f ms each" % want_ms[0],
                "measured %.1f Hz and %.1f Hz, each %.1f ms"
                % (fire[0][0][0], fire[0][1][0], f_ms))
        e_ms = evac[0][0][1]
        res.add(abs(e_ms - want_ms[1]) < 1.0 and evac[1] == 0.5,
                "evac = one tone pulsed %.1f ms on / %.1f ms off" % (want_ms[1],
                                                                     want_ms[1]),
                "tone %.1f Hz, window %.1f ms, audible duty %.3f"
                % (evac[0][0][0], e_ms, evac[1]))
        res.add(gen[1] == 1.0 and abs(gen[0][0][0] - 700.0) < 1.0,
                "general = one continuous tone at 700 Hz",
                "tone %.4f Hz duty %.3f" % (gen[0][0][0], gen[1]))
        sig = lambda t: tuple(sorted(round(f, 1) for f, _ in _siren_shape(cfg, t)[0])) \
            + (_siren_shape(cfg, t)[1],)                    # noqa: E731
        shapes = [sig(t) for t in (TYPE_FIRE, TYPE_EVAC, TYPE_GENERAL)]
        res.add(len(set(shapes)) == 3,
                "the three type codes really are three different sounds",
                "without this the whole differentiation claim could be vacuous: %s"
                % (shapes,))
        res.add(fire[1] == 1.0 and gen[1] == 1.0 and evac[1] == 0.5
                and all(100.0 <= ms <= 1000.0 for _, ms in fire[0]),
                "each alternation is slow enough for an ear to call it two tones",
                "alternation %.1f ms; a siren that swaps every sub-millisecond is "
                "a buzz, and the per-clock bug made exactly that" % f_ms)
        res.add(cfg['held_at_zero'] and _siren_shape(cfg, TYPE_EVAC)[0][0][1] > 0,
                "the pattern counter is held at 0 while the alarm is down",
                "so a takeover always starts on the loud half of its own window")
        # NEGATIVE CONTROL: the shipped-until-tonight form of the line. Hoisting
        # the increment out of the tick guard is not a hypothetical; it is what
        # the file said, and the pass above has to be able to see it.
        code = _strip_comments(SIREN_SRC)
        adv = re.search(r"[ ]*if \(I_en\) S_mod_cnt <= S_mod_cnt \+ 16'd1;\n"
                        r"[ ]*else +S_mod_cnt <= 16'd0;\n", code)
        hoist_end = re.search(r"end else begin\n[ ]*S_tick_acc <= W_tick_next;\n[ ]*end\n",
                              code)
        if adv and hoist_end:
            mutated = (code[:adv.start()] + code[adv.end():hoist_end.end()]
                       + adv.group(0) + code[hoist_end.end():])
            bad = _siren_cfg(mutated)
            slow = _siren_shape(bad, TYPE_EVAC)[0][0][1]
            mod_hz = 1000.0 / (2 * slow)
            res.add(not bad['per_sample'] and abs(slow - want_ms[1] / 520.833) < 1.0,
                    "NEGATIVE CONTROL: the per-clock cadence is caught",
                    "placement read as per-clock=%d, evac window collapses to "
                    "%.3f ms = a %.0f Hz amplitude modulation, not a pulsed blast"
                    % (0 if bad['per_sample'] else 1, slow, mod_hz))
        else:
            res.add(False, "NEGATIVE CONTROL: the per-clock cadence is caught",
                    "mutation did not apply (%d/%d anchors), so this proved nothing"
                    % (1 if adv else 0, 1 if hoist_end else 0))

    # ---- the horn. Same claim, second channel, second arithmetic.
    bparam = _param_src(TOP_SRC, 'buzzer_beep', 'u_buzzer_beep')
    b = _buzzer_cfg(BUZZ_SRC, bparam)
    res.add(not b['error'], "buzzer_beep.v's constants parse, with top's overrides",
            "; ".join(b['error']) or
            "CLK=%d TONE=%d%s WINDOW=%d ms ON fire/evac/gen=%d/%d/%d"
            % (b['CLK_FREQ_HZ'], b['TONE_HZ'],
               " (overridden)" if b['TONE_HZ_overridden'] else "",
               b['WINDOW_MS'], b['ON_FIRE'], b['ON_EVAC'], b['ON_GEN']))
    if b['error']:
        return

    shipped = b['CLK_FREQ_HZ'] / float(2 * b['HALF_TONE'])
    res.add(abs(shipped - b['TONE_HZ']) < 1.0
            and b['CLK_FREQ_HZ'] % (2 * b['HALF_TONE']) == 0,
            "the horn's divider is exact at the shipped constants",
            "%d Hz / (2 x %d) = %.4f Hz, 50%% duty by construction"
            % (b['CLK_FREQ_HZ'], b['HALF_TONE'], shipped))

    # Shrink every rate by the same factor so the walk stays cycle-accurate.
    k = 50
    small_clk, small_tone = b['CLK_FREQ_HZ'] // k // 100, b['TONE_HZ'] // 10
    small_win = b['WINDOW_MS'] // k
    on_ms = {TYPE_FIRE: b['ON_FIRE'] // k, TYPE_EVAC: b['ON_EVAC'] // k,
             TYPE_GENERAL: b['ON_GEN'] // k}
    res.add(small_clk % (2 * (small_clk // small_tone // 2)) == 0 and
            all(b[w] % k == 0 for w in ('WINDOW_MS', 'ON_FIRE', 'ON_EVAC', 'ON_GEN')),
            "the shrunk walk divides exactly, so it is the same arithmetic",
            "clk %d Hz tone %d Hz window %d ms on %s"
            % (small_clk, small_tone, small_win, sorted(on_ms.values())))

    runs = {}
    for t in (TYPE_FIRE, TYPE_EVAC, TYPE_GENERAL):
        runs[t] = _buzzer_walk(small_clk, small_tone, small_win, on_ms[t],
                               n_windows=6)
    ms = small_clk // 1000
    duties = dict((t, _duty_and_gap(runs[t], ms)[0]) for t in runs)
    want_duty = dict((t, on_ms[t] / float(small_win)) for t in on_ms)
    res.add(all(abs(duties[t] - want_duty[t]) < 0.01 for t in duties),
            "each type's sounding fraction is its ON_ms over the window",
            "measured %s want %s"
            % (dict((t, round(v, 3)) for t, v in duties.items()),
               dict((t, round(v, 3)) for t, v in want_duty.items())))
    res.add(len(set(round(v, 3) for v in duties.values())) == 3,
            "three type codes, three horn patterns -- all distinct",
            "duty %s; two identical ones would be one alarm you cannot name blind"
            % (dict((t, round(v, 3)) for t, v in duties.items()),))
    meas = _measured_tone_hz(*runs[TYPE_FIRE], small_clk)
    res.add(meas is not None and abs(meas - small_tone) < 1.0,
            "the tone frequency is measured from O_beep's edges, not from the parameter",
            "%d Hz walked, %d Hz asked for" % (round(meas or 0, 3), small_tone))
    fire_gap = _duty_and_gap(runs[TYPE_FIRE], ms)[1]
    evac_gap = _duty_and_gap(runs[TYPE_EVAC], ms)[1]
    res.add(fire_gap == 0.0 and 1.0 < evac_gap <= (small_win - on_ms[TYPE_EVAC]) + 1,
            "fire is continuous because ON_FIRE == WINDOW_MS, not by a special case",
            "longest silence fire/evac = %.1f/%.1f ms; the comparator can never be "
            "satisfied for fire, so the long blast needs no extra case arm"
            % (fire_gap, evac_gap))
    mute = _buzzer_walk(small_clk, small_tone, small_win, on_ms[TYPE_EVAC], level=0)
    res.add(not any(mute[0]) and not any(mute[1]),
            "VOLM 0 silences the horn, and silence is a driven 0",
            "%d sounding edges, %d beep edges out of %d"
            % (sum(mute[0]), sum(mute[1]), len(mute[0])))

    res.add(b['ladder_guard'] == 'I_alarm && (I_level != 2\'d0)'
            and b['envelope_terms'],
            "the window ladder is armed by the alarm level, never by the envelope",
            "guard reads `%s`, envelope keeps the win_ms compare" % b['ladder_guard'])
    bad = _buzzer_walk(small_clk, small_tone, small_win, on_ms[TYPE_EVAC],
                       ladder='envelope', n_windows=6)
    bad_duty, bad_gap = _duty_and_gap(bad, ms)
    res.add(bad_duty > 0.9 and bad_gap <= 1.0
            and bad_duty - duties[TYPE_EVAC] > 0.5,
            "NEGATIVE CONTROL: envelope-gating the ladder makes every type continuous",
            "evac duty %.3f/%.1f ms silence walked right, %.3f/%.1f ms gated by the "
            "envelope -- the off-period becomes unreachable, the bug this file "
            "already had once" % (duties[TYPE_EVAC],
                                  _duty_and_gap(runs[TYPE_EVAC], ms)[1],
                                  bad_duty, bad_gap))
    threaded = bool(re.search(r"\.EMERGENCY_ENABLE\s*\(\s*EMERGENCY_ENABLE\s*\)",
                              bparam))
    res.add(b['silence_driven'] and b['gated_by_enable']
            and bool(re.search(r"O_beep\s*<=\s*1'b0", _strip_comments(BUZZ_SRC)))
            and threaded,
            "at EMERGENCY_ENABLE=0 the horn has no loads and the pin stays 0",
            "silence-driven=%d enable-gated=%d parameter threaded into the instance=%d"
            % (b['silence_driven'], b['gated_by_enable'], 1 if threaded else 0))


# ---------------------------------------------------------------------------
# Pass K -- the burn-in sequencer, i.e. the 7x24 claim
# ---------------------------------------------------------------------------
def pass_k(res, verbose):
    print("=" * 78)
    print("K. Burn-in sequencer: self-cycling soak, inert in the shipped build")
    print("=" * 78)

    # burn_sec is an integer parameter, so shrink the clock the same way the
    # debouncer does instead of walking 50 M edges per phase.
    per_phase = 1 * 1000 * 5                       # BURN_SEC=1 at 5 ticks/ms
    s = System(burn_sec=1, ticks_per_ms=5)
    phases = []
    s.settle(per_phase // 2 - 2)
    for _ in range(7):
        s.settle(per_phase)
        phases.append((s.st['burn_on'], s.st['req_cmd'], s.st['emg_state']))
    ups = [p for p in phases if p[0]]
    res.add(len(ups) >= 3 and all(p[2] >> 2 for p in ups)
            and all(p[2] == 0 for p in phases if not p[0]),
            "the sequencer takes the panel over and lets go, unattended",
            "7 phases seen: %s" % (phases,))
    types_seen = sorted(set(p[1] for p in ups))
    cycle = [p[1] for p in phases if p[0]]
    res.add(types_seen == [TYPE_FIRE, TYPE_EVAC, TYPE_GENERAL]
            and len(set(cycle)) == 3,
            "every phase walks 1 -> 2 -> 3 -> 1, so a soak visits all three",
            "on-phases requested %s" % (cycle,))
    res.add(all(phases[i][0] != phases[i + 1][0] for i in range(len(phases) - 1)),
            "no ON phase is ever followed by another ON (50% duty, forever)",
            "a stuck sequencer would soak one state and call it 7x24: %s"
            % ([p[0] for p in phases],))

    # Inert in the build anyone is actually going to flash.
    q = System(ticks_per_ms=5)
    q.settle(3 * per_phase)
    res.add(q.burn_sec == 0 and q.st['burn_cnt'] == 0 and q.st['burn_on'] == 0
            and q.st['emg_state'] == 0 and q.st['req_cmd'] == 0,
            "at the shipped BURN_SEC=0 the timer never moves and never self-triggers",
            "burn_cnt=%d burn_on=%d state=%d -- an unrequested alarm on a signage "
            "board is the worst possible bug this feature could have"
            % (q.st['burn_cnt'], q.st['burn_on'], q.st['emg_state']))
    cparam = _param_src(TOP_SRC, 'emergency_ctrl', 'u_emergency_ctrl')
    res.add(bool(re.search(r"\.BURN_SEC\s*\(\s*0\s*\)", cparam)),
            "top ships .BURN_SEC(0), so the sequencer is pruned at synthesis",
            "parameter block is %d chars; the soak generator is a build-time switch"
            % len(cparam))

    # The operator outranks the test generator in the very same cycle.
    r = System(burn_sec=1, ticks_per_ms=5)
    r.settle(40)
    r.st['burn_req_v'] = 1
    r.st['burn_req'] = TYPE_EVAC
    r.st['cmd_emg_set'] = 1
    r.st['cmd_emg'] = TYPE_GENERAL
    r.settle(1)
    res.add(r.st['req_cmd'] == TYPE_GENERAL and r.st['burn_req_v'] == 0,
            "a command and a burn publish in one cycle: the command wins",
            "req_cmd=%d (asked %d, offered %d) and the publish was consumed"
            % (r.st['req_cmd'], TYPE_GENERAL, TYPE_EVAC))

    # A closed contact is not the sequencer's to release.
    h = System(burn_sec=1, ticks_per_ms=5)
    h.pin_aut = 0
    h.settle(40)                                   # let T2 arm and dominate
    off_phases = 0
    stayed = 0
    for _ in range(6):
        h.settle(per_phase)
        if h.st['burn_on'] == 0:
            off_phases += 1
            stayed += 1 if (h.st['emg_state'] >> 2) and \
                (h.st['emg_state'] & 3) == AUTO_TYPE else 0
    res.add(off_phases >= 2 and stayed == off_phases,
            "the sequencer's ALRM 0 cannot release a held hardwire contact",
            "%d off-phases, %d kept the fire alarm up; release is an AND over the "
            "requestors, so a shorted line soaks as a persistent alarm"
            % (off_phases, stayed))
    h.pin_aut = 1
    h.settle(2 * per_phase)
    res.add(h.st['emg_state'] == 0 or (h.st['emg_state'] & 3) != 0,
            "after the contact opens the sequencer is back in charge",
            "state=%d -- nothing latched to the contact's type" % h.st['emg_state'])

    # Model/RTL alignment. The model mirrors two always blocks; if the RTL's
    # sequencer ever starts naming the command input, the mirror is a lie and
    # every check above silently changes meaning.
    ccode = _strip_comments(CTRL_SRC)
    seq = re.search(r"else if \((EMERGENCY_ENABLE && BURN_SEC != 0)\)", ccode)
    load = re.search(r"if \(EMERGENCY_ENABLE && \(I_cmd_emg_set \|\| "
                     r"(\w+)\)\)\s*\n\s*req_cmd <= I_cmd_emg_set \? I_cmd_emg : "
                     r"(\w+);", ccode)
    res.add(bool(seq) and bool(load) and load.group(1) == 'burn_req_v'
            and load.group(2) == 'burn_req',
            "the RTL still splits publish and load the way the model mirrors it",
            "sequencer guard names no command input=%d; the load is a mux with the "
            "operator first=%d" % (bool(seq), bool(load)))
    res.add(bool(re.search(r"burn_req_v <= 1'b0;", ccode))
            and len(re.findall(r"burn_req_v <= 1'b1;", ccode)) == 2,
            "the publish is a one-cycle flag, cleared every edge and set on both steps",
            "the model's req_cmd therefore lags the on/off edge by one clk, which is "
            "why K asserts phases, not exact edges")

    # NEGATIVE CONTROL: drop the release publish and the soak tests one state.
    z = System(burn_sec=1, ticks_per_ms=5, burn_stuck=1)
    z.settle(4 * per_phase)
    res.add((z.st['emg_state'] >> 2) == 1 and z.st['burn_on'] == 0,
            "NEGATIVE CONTROL: a sequencer that never releases is caught",
            "stuck model still has %d on the panel after the timer turned off, so "
            "the 50%% duty check above has an edge" % (z.st['emg_state'],))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--verbose", action="store_true")
    args = ap.parse_args()
    res = Result()
    pass_a(res, args.verbose)
    pass_b(res, args.verbose)
    pass_c(res, args.verbose)
    pass_d(res, args.verbose)
    pass_e(res, args.verbose)
    pass_f(res, args.verbose)
    pass_g(res, args.verbose)
    pass_h(res, args.verbose)
    pass_i(res, args.verbose)
    pass_j(res, args.verbose)
    pass_k(res, args.verbose)
    print("=" * 78)
    total = len(res.rows)
    print("%d/%d checks passed, %d failed" % (total - res.failed, total,
                                              res.failed))
    print("=" * 78)
    sys.exit(1 if res.failed else 0)


if __name__ == "__main__":
    main()
